// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// ChannelSummaryByLevel2Req
type ChannelSummaryByLevel2Req struct {
	Request         *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	Limit           int64                        `json:"limit"`                           // 返回记录数限制
	OrderType       types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	ChannelLevel1Id int64                        `json:"channelLevel1Id"`                 // 一级渠道ID，用于筛选指定一级渠道下的二级渠道
	Lid             []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid      []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
}

// Api 返回API路径
func (r *ChannelSummaryByLevel2Req) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if r.ChannelLevel1Id > 0 {
		params.Add("channelLevel1Id", strconv.FormatInt(r.ChannelLevel1Id, 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/channel/g-level2/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ChannelSummaryByLevel2Req) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ChannelSummaryByLevel2Req) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ChannelSummaryByLevel2Req) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ChannelSummaryByLevel2Req) AuthRequired() bool {
	return true
}

// ChannelSummaryByLevel2Resp
type ChannelSummaryByLevel2Resp struct {
	Total *ChannelSummary       `json:"total"` // 二级渠道汇总统计数据
	List  []SummaryByLevel2List `json:"list"`  // 二级渠道详细统计数据列表
}

// SummaryByLevel2List
type SummaryByLevel2List struct {
	ChannelLevel2Id   int64           `json:"channelLevel2Id"`   // 二级渠道ID
	ChannelLevel2Name string          `json:"channelLevel2Name"` // 二级渠道名称
	Summary           *ChannelSummary `json:"summary"`           // 渠道统计数据
}
