// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
	time "time"
)

// ChannelSummaryByLevel1Req
type ChannelSummaryByLevel1Req struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	Limit      int64                        `json:"limit"`                           // 返回记录数限制
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
}

// Api 返回API路径
func (r *ChannelSummaryByLevel1Req) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/channel/g-level1/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ChannelSummaryByLevel1Req) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ChannelSummaryByLevel1Req) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ChannelSummaryByLevel1Req) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ChannelSummaryByLevel1Req) AuthRequired() bool {
	return true
}

// ChannelSummaryByLevel1Resp
type ChannelSummaryByLevel1Resp struct {
	List []SummaryByLevel1List `json:"list"` // 一级渠道统计数据列表
}

// PassedTimeSpanRequest 时间范围请求参数
type PassedTimeSpanRequest struct {
	Sid      []int64        `json:"sid"`                       // 景区ID列表
	Start    time.Time      `json:"start" validate:"required"` // 开始时间: YYY-MM-DD; 如: 2021-01-01
	End      time.Time      `json:"end" validate:"required"`   // 结束时间: YYY-MM-DD; 如: 2021-01-01
	DateType types.DateType `json:"dateType"`                  // 日期类型(默认 0): 0 (DAILY)按日期范围; 1 (MONTHLY)只处理日期中的年和月然后整月查询; 2 (YEARLY)整年查询
}

// Params 将PassedTimeSpanRequest转换为url.Values
func (p PassedTimeSpanRequest) Params(prefix string) url.Values {
	params := url.Values{}
	if len(p.Sid) > 0 {
		for _, item := range p.Sid {
			params.Add(prefix+"sid", strconv.FormatInt(item, 10))
		}
	}
	if !p.Start.IsZero() {
		params.Add(prefix+"start", p.Start.Format("2006-01-02 15:04:05"))
	}
	if !p.End.IsZero() {
		params.Add(prefix+"end", p.End.Format("2006-01-02 15:04:05"))
	}
	if p.DateType > 0 {
		params.Add(prefix+"dateType", strconv.FormatInt(int64(p.DateType), 10))
	}
	return params
}

// SummaryByLevel1List
type SummaryByLevel1List struct {
	ChannelLevel1Id   int64           `json:"channelLevel1Id"`   // 一级渠道ID
	ChannelLevel1Name string          `json:"channelLevel1Name"` // 一级渠道名称
	Summary           *ChannelSummary `json:"summary"`           // 渠道统计数据
	TicketCountRate   float64         `json:"ticketCountRate"`   // 票量占比
}

// ChannelSummary
type ChannelSummary struct {
	OrderCount  int64 `json:"orderCount"`  // 订单量
	TicketCount int64 `json:"ticketCount"` // 票量
	Amount      int64 `json:"amount"`      // 订单金额（单位：分）
}
