// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// OrderToiStatisticsReq
type OrderToiStatisticsReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 按订单类型的时间范围请求参数
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
}

// Api 返回API路径
func (r *OrderToiStatisticsReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/order/toi-statistics?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *OrderToiStatisticsReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *OrderToiStatisticsReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *OrderToiStatisticsReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *OrderToiStatisticsReq) AuthRequired() bool {
	return true
}

// OrderToiStatisticsResp
type OrderToiStatisticsResp struct {
	Summary    *ToiSummary     `json:"summary"`    // 全部订单汇总统计数据
	Team       *ToiSummaryRate `json:"team"`       // 团队订单统计数据及占比
	Individual *ToiSummaryRate `json:"individual"` // 个人订单统计数据及占比
}

// ToiSummary
type ToiSummary struct {
	Order  int64 `json:"order"`  // 订单数
	Ticket int64 `json:"ticket"` // 票数
	Amount int64 `json:"amount"` // 订单金额（单位：分）
	Verify int64 `json:"verify"` // 验票数
}

// ToiSummaryRate
type ToiSummaryRate struct {
	Order      int64   `json:"order"`      // 订单数
	Ticket     int64   `json:"ticket"`     // 票数
	Amount     int64   `json:"amount"`     // 订单金额（单位：分）
	OrderRate  float64 `json:"orderRate"`  // 订单数占比
	TicketRate float64 `json:"ticketRate"` // 票数占比
	AmountRate float64 `json:"amountRate"` // 金额占比
}
