// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
	time "time"
)

// OrderToiSummaryReq
type OrderToiSummaryReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 按订单类型的时间范围请求参数
	Compare    *types.PassedTimeSpan        `json:"compare"`                         // 对比时间范围请求参数
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
}

// Api 返回API路径
func (r *OrderToiSummaryReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Compare != nil {
		for key, values := range r.Compare.Params("compare.") {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/order/toi-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *OrderToiSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *OrderToiSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *OrderToiSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *OrderToiSummaryReq) AuthRequired() bool {
	return true
}

// OrderToiSummaryResp
type OrderToiSummaryResp struct {
	Total *ToiSummary      `json:"total"` // 团散单汇总统计数据
	List  []ToiSummaryList `json:"list"`  // 按日期维度的团散单统计数据列表
}

// PassedTimeSpan 时间范围
type PassedTimeSpan struct {
	Start time.Time `json:"start"` // 开始时间: YYY-MM-DD; 如: 2021-01-01
	End   time.Time `json:"end"`   // 结束时间: YYY-MM-DD; 如: 2021-01-01
}

// Params 将PassedTimeSpan转换为url.Values
func (p PassedTimeSpan) Params(prefix string) url.Values {
	params := url.Values{}
	if !p.Start.IsZero() {
		params.Add(prefix+"start", p.Start.Format("2006-01-02 15:04:05"))
	}
	if !p.End.IsZero() {
		params.Add(prefix+"end", p.End.Format("2006-01-02 15:04:05"))
	}
	return params
}

// ToiSummaryList
type ToiSummaryList struct {
	Time    int64           `json:"time"`    // 时间戳
	Summary *ToiSummaryRate `json:"summary"` // 团散单统计数据及占比
}
