// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// ProductSummaryByTicketAndChannelReq
type ProductSummaryByTicketAndChannelReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	TicketId   []int64                      `json:"ticketId"`                        // 票种ID列表
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
}

// Api 返回API路径
func (r *ProductSummaryByTicketAndChannelReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if len(r.TicketId) > 0 {
		for _, id := range r.TicketId {
			params.Add("ticketId", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/product/g-ticket-channel/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ProductSummaryByTicketAndChannelReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ProductSummaryByTicketAndChannelReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ProductSummaryByTicketAndChannelReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ProductSummaryByTicketAndChannelReq) AuthRequired() bool {
	return true
}

// ProductSummaryByTicketAndChannelResp
type ProductSummaryByTicketAndChannelResp struct {
	List []SummaryByTicketAndChannelList `json:"list"` // 按票种和渠道维度的销售统计数据列表
}

// SummaryByTicketAndChannelList
type SummaryByTicketAndChannelList struct {
	TicketId        int64   `json:"ticketId"`        // 票种ID
	TicketName      string  `json:"ticketName"`      // 票种名称
	ChannelId       int64   `json:"channelId"`       // 渠道ID
	ChannelName     string  `json:"channelName"`     // 渠道名称
	TicketCount     int64   `json:"ticketCount"`     // 票数
	TicketCountRate float64 `json:"ticketCountRate"` // 票数占比
}
