// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	strconv "strconv"

	types "github.com/piaofutong/odas-sdk/odas/common"
)

// ProductSummaryByTicketReq
type ProductSummaryByTicketReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 按订单类型的时间范围请求参数
	Compare    *types.PassedTimeSpan        `json:"compare"`                         // 对比时间范围参数
	Page       int64                        `json:"page"`                            // 页码
	PageSize   int64                        `json:"pageSize"`                        // 每页大小
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
}

// Api 返回API路径
func (r *ProductSummaryByTicketReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Compare != nil {
		for key, values := range r.Compare.Params("compare.") {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}
	if r.Page > 0 {
		params.Add("page", strconv.FormatInt(r.Page, 10))
	}
	if r.PageSize > 0 {
		params.Add("pageSize", strconv.FormatInt(r.PageSize, 10))
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/product/g-ticket/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ProductSummaryByTicketReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ProductSummaryByTicketReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ProductSummaryByTicketReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ProductSummaryByTicketReq) AuthRequired() bool {
	return true
}

// ProductSummaryByTicketResp
type ProductSummaryByTicketResp struct {
	Pagination *types.Pagination     `json:"pagination"` // 分页信息
	List       []SummaryByTicketList `json:"list"`       // 按票种维度的销售统计数据列表
	Total      *ProductSummary       `json:"total"`      // 销售统计数据汇总
}

// Pagination Common structures
type Pagination struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
	Pages    int64 `json:"pages"`
}

// SummaryByTicketList
type SummaryByTicketList struct {
	TicketId    int64               `json:"ticketId"`    // 票种ID
	TicketName  string              `json:"ticketName"`  // 票种名称
	Summary     *ProductSummary     `json:"summary"`     // 票销售统计数据
	Compare     *ProductSummary     `json:"compare"`     // 票销售统计数据 - 对比时间段
	CompareRate *ProductSummaryRate `json:"compareRate"` // 对比期间的增长率
}

// ProductSummary
type ProductSummary struct {
	TicketCount int64 `json:"ticketCount"` // 票数
	Amount      int64 `json:"amount"`      // 金额（单位：分）
}

// ProductSummaryRate
type ProductSummaryRate struct {
	TicketCount float64 `json:"ticketCount"` // 票数增长率
	Amount      float64 `json:"amount"`      // 金额增长率
}
