// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// ReportTerminalSummaryBySiteAndDateReq
type ReportTerminalSummaryBySiteAndDateReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request" validate:"required"`     // 必填请求参数
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
}

// Api 返回API路径
func (r *ReportTerminalSummaryBySiteAndDateReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/report/g-site-date/terminal-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ReportTerminalSummaryBySiteAndDateReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ReportTerminalSummaryBySiteAndDateReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ReportTerminalSummaryBySiteAndDateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ReportTerminalSummaryBySiteAndDateReq) AuthRequired() bool {
	return true
}

// ReportTerminalSummaryBySiteAndDateResp
type ReportTerminalSummaryBySiteAndDateResp struct {
	Total *TerminalSummary                   `json:"total"` // 票验证汇总统计数据
	List  []TerminalSummaryBySiteAndDateList `json:"list"`  // 票验证统计维度数据列表
}

// TerminalSummaryBySiteAndDateList
type TerminalSummaryBySiteAndDateList struct {
	SiteId   int64            `json:"siteId"`   // 站点ID
	SiteName string           `json:"siteName"` // 站点名称
	Date     string           `json:"date"`     // 日期（YYYY-MM-DD格式）
	Summary  *TerminalSummary `json:"summary"`  // 票验证统计数据
}
