// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// ReportTerminalSummaryByProductReq
type ReportTerminalSummaryByProductReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	Limit      int64                        `json:"limit"`                           // 返回记录数限制
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
}

// Api 返回API路径
func (r *ReportTerminalSummaryByProductReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/report/g-product/terminal-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ReportTerminalSummaryByProductReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ReportTerminalSummaryByProductReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ReportTerminalSummaryByProductReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ReportTerminalSummaryByProductReq) AuthRequired() bool {
	return true
}

// ReportTerminalSummaryByProductResp
type ReportTerminalSummaryByProductResp struct {
	Total *TerminalSummary               `json:"total"` // 终端验证汇总统计数据
	List  []TerminalSummaryByProductList `json:"list"`  // 各终端验证统计数据列表
}

// TerminalSummaryByProductList
type TerminalSummaryByProductList struct {
	ProductId   int64            `json:"productId"`   // 产品ID
	ProductName string           `json:"productName"` // 产品名称
	Summary     *TerminalSummary `json:"summary"`     // 终端验证统计数据
}
