// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"github.com/piaofutong/odas-sdk/odas/common"
	"net/url"
	"strconv"
)

// ReportSummaryReq  报告汇总请求
type ReportSummaryReq struct {
	Request   common.PassedTimeSpanV4Request `json:"request,omitempty"`
	OrderType int32                          `json:"orderType,omitempty"`
}

// Api 返回API路径
func (r *ReportSummaryReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	return fmt.Sprintf("/v5/basic_analyze/report/report-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ReportSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ReportSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ReportSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ReportSummaryReq) AuthRequired() bool {
	return true
}

// ReportSummaryResp  订单汇总
type ReportSummaryResp struct {
	OrderNum             int64 `json:"orderNum,omitempty"`             // 预定订单数量
	OrderTicket          int64 `json:"orderTicket,omitempty"`          // 预定订单票数
	OrderAmount          int64 `json:"orderAmount,omitempty"`          // 预定订单金额
	OrderCostMoney       int64 `json:"orderCostMoney,omitempty"`       // 预定订单成本
	VerifiedNum          int64 `json:"verifiedNum,omitempty"`          // 验证数量
	VerifiedTicket       int64 `json:"verifiedTicket,omitempty"`       // 验证票数
	VerifiedAmount       int64 `json:"verifiedAmount,omitempty"`       // 验证金额
	VerifiedCostMoney    int64 `json:"verifiedCostMoney,omitempty"`    // 验证成本
	FinishedNum          int64 `json:"finishedNum,omitempty"`          // 完结数量
	FinishedTicket       int64 `json:"finishedTicket,omitempty"`       // 完结票数
	FinishedAmount       int64 `json:"finishedAmount,omitempty"`       // 完结金额
	FinishedCostMoney    int64 `json:"finishedCostMoney,omitempty"`    // 完结成本
	RevokedNum           int64 `json:"revokedNum,omitempty"`           // 撤销数量
	RevokedTicket        int64 `json:"revokedTicket,omitempty"`        // 撤销票数
	RevokedAmount        int64 `json:"revokedAmount,omitempty"`        // 撤销金额
	RevokedCostMoney     int64 `json:"revokedCostMoney,omitempty"`     // 撤销成本
	CancelNum            int64 `json:"cancelNum,omitempty"`            // 取消数量
	CancelTicket         int64 `json:"cancelTicket,omitempty"`         // 取消票数
	CancelAmount         int64 `json:"cancelAmount,omitempty"`         // 取消金额
	CancelCostMoney      int64 `json:"cancelCostMoney,omitempty"`      // 取消成本
	PrintNum             int64 `json:"printNum,omitempty"`             // 取票数量
	AfterSaleTicketNum   int64 `json:"afterSaleTicketNum,omitempty"`   // 售后票数
	AfterSaleRefundMoney int64 `json:"afterSaleRefundMoney,omitempty"` // 售后退款金额
	AfterSaleIncomeMoney int64 `json:"afterSaleIncomeMoney,omitempty"` // 售后收入金额

}
