// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// ReportCheckinSummaryReq
type ReportCheckinSummaryReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
}

// Api 返回API路径
func (r *ReportCheckinSummaryReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/report/g-date/checkin-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ReportCheckinSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ReportCheckinSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ReportCheckinSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ReportCheckinSummaryReq) AuthRequired() bool {
	return true
}

// ReportCheckinSummaryResp
type ReportCheckinSummaryResp struct {
	Total *CheckinSummaryTotal `json:"total"` // 检票汇总统计数据
	List  []CheckinSummaryList `json:"list"`  // 按日期分组的检票统计数据列表
}

// CheckinSummaryTotal
type CheckinSummaryTotal struct {
	Count int64 `json:"count"` // 检票数量
}

// CheckinSummaryList
type CheckinSummaryList struct {
	Date    string               `json:"date"`    // 日期（YYYY-MM-DD格式）
	Summary *CheckinSummaryTotal `json:"summary"` // 检票统计数据
}
