// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// ReportOrderStatisticsReq 订单统计请求参数
type ReportOrderStatisticsReq struct {
	Request        *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	YearOnYear     bool                         `json:"yearOnYear"`                      // 是否获取同比数据
	PeriodOnPeriod bool                         `json:"periodOnPeriod"`                  // 是否获取环比数据
	OrderType      types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid            []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid     []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
}

// Api 返回API路径
func (r *ReportOrderStatisticsReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.YearOnYear {
		params.Add("yearOnYear", "true")
	}
	if r.PeriodOnPeriod {
		params.Add("periodOnPeriod", "true")
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/report/order-statistics?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ReportOrderStatisticsReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ReportOrderStatisticsReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ReportOrderStatisticsReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ReportOrderStatisticsReq) AuthRequired() bool {
	return true
}

// ReportOrderStatisticsResp
type ReportOrderStatisticsResp struct {
	Summary        *OrderSummary               `json:"summary"`        // 订单汇总统计数据
	YearOnYear     *OrderCompareStatisticsRate `json:"yearOnYear"`     // 同比增长率数据
	PeriodOnPeriod *OrderCompareStatisticsRate `json:"periodOnPeriod"` // 环比增长率数据
}

// OrderSummary
type OrderSummary struct {
	OrderNum             int64 `json:"orderNum"`             // 预定订单数量
	OrderTicket          int64 `json:"orderTicket"`          // 预定订单票数
	OrderAmount          int64 `json:"orderAmount"`          // 预定订单金额（单位：分）
	OrderCostMoney       int64 `json:"orderCostMoney"`       // 预定订单成本（单位：分）
	VerifiedNum          int64 `json:"verifiedNum"`          // 验证数量
	VerifiedTicket       int64 `json:"verifiedTicket"`       // 验证票数
	VerifiedAmount       int64 `json:"verifiedAmount"`       // 验证金额（单位：分）
	VerifiedCostMoney    int64 `json:"verifiedCostMoney"`    // 验证成本（单位：分）
	FinishedNum          int64 `json:"finishedNum"`          // 完结数量
	FinishedTicket       int64 `json:"finishedTicket"`       // 完结票数
	FinishedAmount       int64 `json:"finishedAmount"`       // 完结金额（单位：分）
	FinishedCostMoney    int64 `json:"finishedCostMoney"`    // 完结成本（单位：分）
	RevokedNum           int64 `json:"revokedNum"`           // 撤销数量
	RevokedTicket        int64 `json:"revokedTicket"`        // 撤销票数
	RevokedAmount        int64 `json:"revokedAmount"`        // 撤销金额（单位：分）
	RevokedCostMoney     int64 `json:"revokedCostMoney"`     // 撤销成本（单位：分）
	CancelNum            int64 `json:"cancelNum"`            // 取消数量
	CancelTicket         int64 `json:"cancelTicket"`         // 取消票数
	CancelAmount         int64 `json:"cancelAmount"`         // 取消金额（单位：分）
	CancelCostMoney      int64 `json:"cancelCostMoney"`      // 取消成本（单位：分）
	PrintNum             int64 `json:"printNum"`             // 取票数量
	AfterSaleTicketNum   int64 `json:"afterSaleTicketNum"`   // 售后票数
	AfterSaleRefundMoney int64 `json:"afterSaleRefundMoney"` // 售后退款金额（单位：分）
	AfterSaleIncomeMoney int64 `json:"afterSaleIncomeMoney"` // 售后收入金额（单位：分）
}

// OrderCompareStatisticsRate
type OrderCompareStatisticsRate struct {
	OrderNum             float64 `json:"orderNum"`             // 预定订单数量增长率
	OrderTicket          float64 `json:"orderTicket"`          // 预定订单票数增长率
	OrderAmount          float64 `json:"orderAmount"`          // 预定订单金额增长率
	OrderCostMoney       float64 `json:"orderCostMoney"`       // 预定订单成本增长率
	VerifiedNum          float64 `json:"verifiedNum"`          // 验证数量增长率
	VerifiedTicket       float64 `json:"verifiedTicket"`       // 验证票数增长率
	VerifiedAmount       float64 `json:"verifiedAmount"`       // 验证金额增长率
	VerifiedCostMoney    float64 `json:"verifiedCostMoney"`    // 验证成本增长率
	FinishedNum          float64 `json:"finishedNum"`          // 完结数量增长率
	FinishedTicket       float64 `json:"finishedTicket"`       // 完结票数增长率
	FinishedAmount       float64 `json:"finishedAmount"`       // 完结金额增长率
	FinishedCostMoney    float64 `json:"finishedCostMoney"`    // 完结成本增长率
	RevokedNum           float64 `json:"revokedNum"`           // 撤销数量增长率
	RevokedTicket        float64 `json:"revokedTicket"`        // 撤销票数增长率
	RevokedAmount        float64 `json:"revokedAmount"`        // 撤销金额增长率
	RevokedCostMoney     float64 `json:"revokedCostMoney"`     // 撤销成本增长率
	CancelNum            float64 `json:"cancelNum"`            // 取消数量增长率
	CancelTicket         float64 `json:"cancelTicket"`         // 取消票数增长率
	CancelAmount         float64 `json:"cancelAmount"`         // 取消金额增长率
	CancelCostMoney      float64 `json:"cancelCostMoney"`      // 取消成本增长率
	PrintNum             float64 `json:"printNum"`             // 取票数量增长率
	AfterSaleTicketNum   float64 `json:"afterSaleTicketNum"`   // 售后票数增长率
	AfterSaleRefundMoney float64 `json:"afterSaleRefundMoney"` // 售后退款金额增长率
	AfterSaleIncomeMoney float64 `json:"afterSaleIncomeMoney"` // 售后收入金额增长率
}
