// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// ReportOrderSummaryByTicketReq
type ReportOrderSummaryByTicketReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	Limit      int64                        `json:"limit"`                           // 返回记录数限制
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	TicketId   []int64                      `json:"ticketId"`                        // 票种ID列表
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	OrderBy    string                       `json:"orderBy"`                         // 排序方式：orderTicket（按预定票数排序） verifiedTicket(按验证票数排序) verifiedAmount(按验证金额排序)
}

// Api 返回API路径
func (r *ReportOrderSummaryByTicketReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.TicketId) > 0 {
		for _, id := range r.TicketId {
			params.Add("ticketId", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if r.OrderBy != "" {
		params.Add("orderBy", r.OrderBy)
	}
	return fmt.Sprintf("/v5/basic_analyze/report/g-ticket/order-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ReportOrderSummaryByTicketReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ReportOrderSummaryByTicketReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ReportOrderSummaryByTicketReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ReportOrderSummaryByTicketReq) AuthRequired() bool {
	return true
}

// ReportOrderSummaryByTicketResp
type ReportOrderSummaryByTicketResp struct {
	Total *OrderSummary              `json:"total"` // 订单汇总统计数据
	List  []OrderSummaryByTicketList `json:"list"`  // 按票种分组的订单统计数据列表
}

// OrderSummaryByTicketList
type OrderSummaryByTicketList struct {
	TicketId   int64         `json:"ticketId"`   // 票种ID
	TicketName string        `json:"ticketName"` // 票种名称
	Summary    *OrderSummary `json:"summary"`    // 订单统计数据
}
