// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"github.com/piaofutong/odas-sdk/odas/common"
	"net/url"
)

// OrderSummaryReq  订单汇总请求
type OrderSummaryReq struct {
	Request common.PassedTimeSpanByOrderTypeV4Request `json:"request,omitempty"`
	Compare bool                                      `json:"compare,omitempty"`
}

// Api 返回API路径
func (r *OrderSummaryReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	if r.Compare {
		params.Add("compare", "true")
	}
	return fmt.Sprintf("/v5/basic_analyze/report/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *OrderSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *OrderSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *OrderSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *OrderSummaryReq) AuthRequired() bool {
	return true
}

// OrderSummaryResp  订单汇总响应
type OrderSummaryResp struct {
	OrderTicket     int64   `json:"orderTicket,omitempty"`
	MomOrderTicket  float64 `json:"momOrderTicket,omitempty"`
	YoyOrderTicket  float64 `json:"yoyOrderTicket,omitempty"`
	VerifyTicket    int64   `json:"verifyTicket,omitempty"`
	MomVerifyTicket float64 `json:"momVerifyTicket,omitempty"`
	YoyVerifyTicket float64 `json:"yoyVerifyTicket,omitempty"`
	RefundTicket    int64   `json:"refundTicket,omitempty"`
	MomRefundTicket float64 `json:"momRefundTicket,omitempty"`
	YoyRefundTicket float64 `json:"yoyRefundTicket,omitempty"`
	OrderAmount     int64   `json:"orderAmount,omitempty"`
	MomOrderAmount  float64 `json:"momOrderAmount,omitempty"`
	YoyOrderAmount  float64 `json:"yoyOrderAmount,omitempty"`
	VerifyAmount    int64   `json:"verifyAmount,omitempty"`
	MomVerifyAmount float64 `json:"momVerifyAmount,omitempty"`
	YoyVerifyAmount float64 `json:"yoyVerifyAmount,omitempty"`
	RefundAmount    int64   `json:"refundAmount,omitempty"`
	MomRefundAmount float64 `json:"momRefundAmount,omitempty"`
	YoyRefundAmount float64 `json:"yoyRefundAmount,omitempty"`
}
