// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"github.com/piaofutong/odas-sdk/odas/common"
	"net/url"
	"strconv"
	"time"
)

// ToiSummaryReq  时间段内订单汇总请求
type ToiSummaryReq struct {
	Request common.PassedTimeSpanByOrderTypeV4Request `json:"request,omitempty"`
	Compare *common.PassedTimeBetween                 `json:"compare,omitempty"`
}

// Api 返回API路径
func (r *ToiSummaryReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	if r.Compare != nil {
		for key, values := range r.Compare.Params("compare.") {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/order/toi-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ToiSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ToiSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ToiSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ToiSummaryReq) AuthRequired() bool {
	return true
}

// ToiSummaryResp  时间段内订单汇总响应
type ToiSummaryResp struct {
	Total ToiSummary        `json:"total,omitempty"`
	List  []*ToiSummaryList `json:"list,omitempty"`
}

// PassedTimeBetween  时间范围
type PassedTimeBetween struct {
	Start time.Time `json:"start,omitempty"`
	End   time.Time `json:"end,omitempty"`
}

// Params 将PassedTimeBetween转换为url.Values
func (p PassedTimeBetween) Params(prefix string) url.Values {
	params := url.Values{}
	if !p.Start.IsZero() {
		params.Add(prefix+"start", p.Start.Format("2006-01-02 15:04:05"))
	}
	if !p.End.IsZero() {
		params.Add(prefix+"end", p.End.Format("2006-01-02 15:04:05"))
	}
	return params
}

// ToiSummaryList  TOI汇总列表
type ToiSummaryList struct {
	Time    int64          `json:"time,omitempty"`
	Summary ToiSummaryRate `json:"summary,omitempty"`
}

// Params 将ToiSummaryList转换为url.Values
func (p ToiSummaryList) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Time > 0 {
		params.Add(prefix+"time", strconv.FormatInt(p.Time, 10))
	}
	for key, values := range p.Summary.Params(prefix + "summary.") {
		for _, value := range values {
			params.Add(key, value)
		}
	}
	return params
}
