// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"github.com/piaofutong/odas-sdk/odas/common"
	"net/url"
	"strconv"
)

// ToiStatisticsReq  时间段内订单统计请求
type ToiStatisticsReq struct {
	Request common.PassedTimeSpanV4Request `json:"request,omitempty"`
}

// Api 返回API路径
func (r *ToiStatisticsReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	return fmt.Sprintf("/v5/basic_analyze/order/toi-statistics?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ToiStatisticsReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ToiStatisticsReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ToiStatisticsReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ToiStatisticsReq) AuthRequired() bool {
	return true
}

// ToiStatisticsResp  时间段内订单统计响应
type ToiStatisticsResp struct {
	Summary    ToiSummary     `json:"summary,omitempty"`    // 全部
	Team       ToiSummaryRate `json:"team,omitempty"`       // 团队
	Individual ToiSummaryRate `json:"individual,omitempty"` // 个人

}

// ToiSummary  TOI汇总
type ToiSummary struct {
	Order  int64 `json:"order,omitempty"`
	Ticket int64 `json:"ticket,omitempty"`
	Amount int64 `json:"amount,omitempty"`
	Verify int64 `json:"verify,omitempty"`
}

// Params 将ToiSummary转换为url.Values
func (p ToiSummary) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Order > 0 {
		params.Add(prefix+"order", strconv.FormatInt(p.Order, 10))
	}
	if p.Ticket > 0 {
		params.Add(prefix+"ticket", strconv.FormatInt(p.Ticket, 10))
	}
	if p.Amount > 0 {
		params.Add(prefix+"amount", strconv.FormatInt(p.Amount, 10))
	}
	if p.Verify > 0 {
		params.Add(prefix+"verify", strconv.FormatInt(p.Verify, 10))
	}
	return params
}

// ToiSummaryRate  TOI汇总比率
type ToiSummaryRate struct {
	Order      int64   `json:"order,omitempty"`
	Ticket     int64   `json:"ticket,omitempty"`
	Amount     int64   `json:"amount,omitempty"`
	OrderRate  float64 `json:"orderRate,omitempty"`
	TicketRate float64 `json:"ticketRate,omitempty"`
	AmountRate float64 `json:"amountRate,omitempty"`
}

// Params 将ToiSummaryRate转换为url.Values
func (p ToiSummaryRate) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Order > 0 {
		params.Add(prefix+"order", strconv.FormatInt(p.Order, 10))
	}
	if p.Ticket > 0 {
		params.Add(prefix+"ticket", strconv.FormatInt(p.Ticket, 10))
	}
	if p.Amount > 0 {
		params.Add(prefix+"amount", strconv.FormatInt(p.Amount, 10))
	}
	if p.OrderRate > 0 {
		params.Add(prefix+"orderRate", fmt.Sprintf("%v", p.OrderRate))
	}
	if p.TicketRate > 0 {
		params.Add(prefix+"ticketRate", fmt.Sprintf("%v", p.TicketRate))
	}
	if p.AmountRate > 0 {
		params.Add(prefix+"amountRate", fmt.Sprintf("%v", p.AmountRate))
	}
	return params
}
