// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"
	"strconv"
)

// TemporaryBookingSummaryReq TemporaryBookingSummary请求
type TemporaryBookingSummaryReq struct {
	Sid int64 `json:"sid,omitempty"`

}

// Api 返回API路径
func (r *TemporaryBookingSummaryReq) Api() string {
	params := url.Values{}
	if r.Sid > 0 {
		params.Add("sid", strconv.FormatInt(r.Sid, 10))
	}
	return fmt.Sprintf("/v5/tourist/temporary-booking/last-day-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *TemporaryBookingSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *TemporaryBookingSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *TemporaryBookingSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *TemporaryBookingSummaryReq) AuthRequired() bool {
	return true
}


// TemporaryBookingSummaryResp TemporaryBookingSummary响应
type TemporaryBookingSummaryResp struct {
	Total TemporaryBookingSummaryTotal `json:"total,omitempty"`
	List []*TemporaryBookingSummaryList `json:"list,omitempty"`

}



// TemporaryBookingSummaryTotal TemporaryBookingSummaryTotal
type TemporaryBookingSummaryTotal struct {
	Temp int64 `json:"temp,omitempty"`
	Booking int64 `json:"booking,omitempty"`

}

// Params 将TemporaryBookingSummaryTotal转换为url.Values
func (p TemporaryBookingSummaryTotal) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Temp > 0 {
		params.Add(prefix+"temp", strconv.FormatInt(p.Temp, 10))
	}
	if p.Booking > 0 {
		params.Add(prefix+"booking", strconv.FormatInt(p.Booking, 10))
	}
	return params
}


// TemporaryBookingSummaryList TemporaryBookingSummaryList
type TemporaryBookingSummaryList struct {
	Time string `json:"time,omitempty"`
	Temp int64 `json:"temp,omitempty"`
	Booking int64 `json:"booking,omitempty"`

}

// Params 将TemporaryBookingSummaryList转换为url.Values
func (p TemporaryBookingSummaryList) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Time != "" {
		params.Add(prefix+"time", p.Time)
	}
	if p.Temp > 0 {
		params.Add(prefix+"temp", strconv.FormatInt(p.Temp, 10))
	}
	if p.Booking > 0 {
		params.Add(prefix+"booking", strconv.FormatInt(p.Booking, 10))
	}
	return params
}


