// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package terminal

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// DevicesListReq 设备列表查询请求参数
type DevicesListReq struct {
	Sid        []int64 `json:"sid"`        // 景区ID列表
	Page       int64   `json:"page"`       // 当前页码
	PageSize   int64   `json:"pageSize"`   // 每页数量
	DeviceType int64   `json:"deviceType"` // 设备类型 1:手持机，2：自助机，3：闸机，4：win自助机，5：web云票务
}

// Api 返回API路径
func (r *DevicesListReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if r.Page > 0 {
		params.Add("page", strconv.FormatInt(r.Page, 10))
	}
	if r.PageSize > 0 {
		params.Add("pageSize", strconv.FormatInt(r.PageSize, 10))
	}
	if r.DeviceType > 0 {
		params.Add("deviceType", strconv.FormatInt(r.DeviceType, 10))
	}
	return fmt.Sprintf("/v5/terminal/devices?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *DevicesListReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *DevicesListReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *DevicesListReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *DevicesListReq) AuthRequired() bool {
	return true
}

// DevicesListResp 设备列表查询响应结果
type DevicesListResp struct {
	List       []StatListData    `json:"list"`       // 设备详情列表
	Pagination *types.Pagination `json:"pagination"` // 分页信息
}

// StatListData 设备详细信息
type StatListData struct {
	Sid            int64  `json:"sid"`            // 设备ID
	DeviceName     string `json:"deviceName"`     // 设备名称
	DeviceKey      string `json:"deviceKey"`      // 设备特征码
	SiteId         int64  `json:"siteId"`         // 设备站点ID
	Location       string `json:"location"`       // 设备站点位置
	Status         int64  `json:"status"`         // 设备网络状态ID
	StatusText     string `json:"statusText"`     // 设备网络状态描述（在线/离线）
	ActiveTimeText string `json:"activeTimeText"` // 启用时间文本格式 - 2006-01-02 15:04
	TodayIn        *int64 `json:"todayIn"`        // 今日入园人数
	TodayOut       *int64 `json:"todayOut"`       // 今日出园人数
}

// Pagination Common structures
type Pagination struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
	Pages    int64 `json:"pages"`
}
