// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"
	"github.com/piaofutong/odas-sdk/odas/request/common"
	"strconv"
)

// OrderSummaryByTicketReq OrderSummaryByTicket请求
type OrderSummaryByTicketReq struct {
	Request common.PassedTimeSpanByOrderTypeV4Request `json:"request,omitempty"`
	Limit int64 `json:"limit,omitempty"`
	TicketId []int64 `json:"ticketId,omitempty"`

}

// Api 返回API路径
func (r *OrderSummaryByTicketReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if len(r.TicketId) > 0 {
		for _, id := range r.TicketId {
			params.Add("ticketId", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/report/g-ticket/order-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *OrderSummaryByTicketReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *OrderSummaryByTicketReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *OrderSummaryByTicketReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *OrderSummaryByTicketReq) AuthRequired() bool {
	return true
}


// OrderSummaryByTicketResp OrderSummaryByTicket响应
type OrderSummaryByTicketResp struct {
	Total OrderSummary `json:"total,omitempty"`
	List []*OrderSummaryByTicketList `json:"list,omitempty"`

}



// OrderSummaryByTicketList OrderSummaryByTicketList
type OrderSummaryByTicketList struct {
	TicketId int64 `json:"ticketId,omitempty"`
	TicketName string `json:"ticketName,omitempty"`
	Summary OrderSummary `json:"summary,omitempty"`

}

// Params 将OrderSummaryByTicketList转换为url.Values
func (p OrderSummaryByTicketList) Params(prefix string) url.Values {
	params := url.Values{}
	if p.TicketId > 0 {
		params.Add(prefix+"ticketId", strconv.FormatInt(p.TicketId, 10))
	}
	if p.TicketName != "" {
		params.Add(prefix+"ticketName", p.TicketName)
	}
	for key, values := range p.Summary.Params(prefix+"summary.") {
		for _, value := range values {
			params.Add(key, value)
		}
	}
	return params
}


