// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"
	"github.com/piaofutong/odas-sdk/odas/request/common"
	"strconv"
)

// ReportSummaryReq ReportSummary请求
type ReportSummaryReq struct {
	Request common.PassedTimeSpanV4Request `json:"request,omitempty"`
	OrderType int32 `json:"orderType,omitempty"`

}

// Api 返回API路径
func (r *ReportSummaryReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	return fmt.Sprintf("/v5/basic_analyze/report/report-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ReportSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ReportSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ReportSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ReportSummaryReq) AuthRequired() bool {
	return true
}


// ReportSummaryResp ReportSummary响应
type ReportSummaryResp struct {
	OrderNum int64 `json:"orderNum,omitempty"`
	OrderTicket int64 `json:"orderTicket,omitempty"`
	OrderAmount int64 `json:"orderAmount,omitempty"`
	OrderCostMoney int64 `json:"orderCostMoney,omitempty"`
	VerifiedNum int64 `json:"verifiedNum,omitempty"`
	VerifiedTicket int64 `json:"verifiedTicket,omitempty"`
	VerifiedAmount int64 `json:"verifiedAmount,omitempty"`
	VerifiedCostMoney int64 `json:"verifiedCostMoney,omitempty"`
	FinishedNum int64 `json:"finishedNum,omitempty"`
	FinishedTicket int64 `json:"finishedTicket,omitempty"`
	FinishedAmount int64 `json:"finishedAmount,omitempty"`
	FinishedCostMoney int64 `json:"finishedCostMoney,omitempty"`
	RevokedNum int64 `json:"revokedNum,omitempty"`
	RevokedTicket int64 `json:"revokedTicket,omitempty"`
	RevokedAmount int64 `json:"revokedAmount,omitempty"`
	RevokedCostMoney int64 `json:"revokedCostMoney,omitempty"`
	CancelNum int64 `json:"cancelNum,omitempty"`
	CancelTicket int64 `json:"cancelTicket,omitempty"`
	CancelAmount int64 `json:"cancelAmount,omitempty"`
	CancelCostMoney int64 `json:"cancelCostMoney,omitempty"`
	PrintNum int64 `json:"printNum,omitempty"`
	AfterSaleTicketNum int64 `json:"afterSaleTicketNum,omitempty"`
	AfterSaleRefundMoney int64 `json:"afterSaleRefundMoney,omitempty"`
	AfterSaleIncomeMoney int64 `json:"afterSaleIncomeMoney,omitempty"`

}



