// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"
	"github.com/piaofutong/odas-sdk/odas/request/common"
	"github.com/piaofutong/odas-sdk/odas/request/types"
	"strconv"
)

// SummaryByLevel1AndLevel1NameReq SummaryByLevel1AndLevel1Name请求
type SummaryByLevel1AndLevel1NameReq struct {
	Request *common.PassedTimeSpanV4Request `json:"request,omitempty"`
	Limit int64 `json:"limit,omitempty"`
	OrderType types.OrderType `json:"orderType,omitempty"`

}

// Api 返回API路径
func (r *SummaryByLevel1AndLevel1NameReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	return fmt.Sprintf("/v5/basic_analyze/channel/g-level1-level1name/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *SummaryByLevel1AndLevel1NameReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *SummaryByLevel1AndLevel1NameReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *SummaryByLevel1AndLevel1NameReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *SummaryByLevel1AndLevel1NameReq) AuthRequired() bool {
	return true
}


// SummaryByLevel1AndLevel1NameResp SummaryByLevel1AndLevel1Name响应
type SummaryByLevel1AndLevel1NameResp struct {
	Total ChannelSummary `json:"total,omitempty"`
	List []*SummaryByLevel1AndLevel1NameList `json:"list,omitempty"`

}



// SummaryByLevel1AndLevel1NameList SummaryByLevel1AndLevel1NameList
type SummaryByLevel1AndLevel1NameList struct {
	ChannelLevel1Id int64 `json:"channelLevel1Id,omitempty"`
	ChannelLevel1Name string `json:"channelLevel1Name,omitempty"`
	Summary ChannelSummary `json:"summary,omitempty"`

}

// Params 将SummaryByLevel1AndLevel1NameList转换为url.Values
func (p SummaryByLevel1AndLevel1NameList) Params(prefix string) url.Values {
	params := url.Values{}
	if p.ChannelLevel1Id > 0 {
		params.Add(prefix+"channelLevel1Id", strconv.FormatInt(p.ChannelLevel1Id, 10))
	}
	if p.ChannelLevel1Name != "" {
		params.Add(prefix+"channelLevel1Name", p.ChannelLevel1Name)
	}
	for key, values := range p.Summary.Params(prefix+"summary.") {
		for _, value := range values {
			params.Add(key, value)
		}
	}
	return params
}


