// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package basic_analyze

import (
	"fmt"
	"net/url"
	"github.com/piaofutong/odas-sdk/odas/request/common"
	"strconv"
)

// SummaryByTicketAndDayReq SummaryByTicketAndDay请求
type SummaryByTicketAndDayReq struct {
	Request common.PassedTimeSpanV4Request `json:"request,omitempty"`
	TicketId []int64 `json:"ticketId,omitempty"`

}

// Api 返回API路径
func (r *SummaryByTicketAndDayReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	if len(r.TicketId) > 0 {
		for _, id := range r.TicketId {
			params.Add("ticketId", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/basic_analyze/product/g-ticket-day/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *SummaryByTicketAndDayReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *SummaryByTicketAndDayReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *SummaryByTicketAndDayReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *SummaryByTicketAndDayReq) AuthRequired() bool {
	return true
}


// SummaryByTicketAndDayResp SummaryByTicketAndDay响应
type SummaryByTicketAndDayResp struct {
	List []*SummaryByTicketAndDayList `json:"list,omitempty"`

}



// SummaryByTicketAndDayList SummaryByTicketAndDayList
type SummaryByTicketAndDayList struct {
	TicketId int64 `json:"ticketId,omitempty"`
	TicketName string `json:"ticketName,omitempty"`
	Date string `json:"date,omitempty"`
	TicketCount int64 `json:"ticketCount,omitempty"`

}

// Params 将SummaryByTicketAndDayList转换为url.Values
func (p SummaryByTicketAndDayList) Params(prefix string) url.Values {
	params := url.Values{}
	if p.TicketId > 0 {
		params.Add(prefix+"ticketId", strconv.FormatInt(p.TicketId, 10))
	}
	if p.TicketName != "" {
		params.Add(prefix+"ticketName", p.TicketName)
	}
	if p.Date != "" {
		params.Add(prefix+"date", p.Date)
	}
	if p.TicketCount > 0 {
		params.Add(prefix+"ticketCount", strconv.FormatInt(p.TicketCount, 10))
	}
	return params
}


