// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"
	"strconv"
)

// AmendmentGetReq AmendmentGet请求
type AmendmentGetReq struct {
	Gid int64 `json:"gid,omitempty"`

}

// Api 返回API路径
func (r *AmendmentGetReq) Api() string {
	params := url.Values{}
	if r.Gid > 0 {
		params.Add("gid", strconv.FormatInt(r.Gid, 10))
	}
	return fmt.Sprintf("/v5/inout/amendment/get?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *AmendmentGetReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *AmendmentGetReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *AmendmentGetReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AmendmentGetReq) AuthRequired() bool {
	return true
}


// AmendmentGetResp AmendmentGet响应
type AmendmentGetResp struct {
	Id int64 `json:"id,omitempty"`
	Gid int64 `json:"gid,omitempty"`
	Switch int64 `json:"switch,omitempty"`
	Type int64 `json:"type,omitempty"`
	InPlus int64 `json:"inPlus,omitempty"`
	OutPlus int64 `json:"outPlus,omitempty"`
	InCoefficient float32 `json:"inCoefficient,omitempty"`
	OutCoefficient float32 `json:"outCoefficient,omitempty"`
	DownTime string `json:"downTime,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`

}



