// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"encoding/json"
)

// AuthorizationDeleteReq AuthorizationDelete请求
type AuthorizationDeleteReq struct {
	Id int64 `json:"id,omitempty"`

}

// Api 返回API路径
func (r *AuthorizationDeleteReq) Api() string {
	// POST/PUT/DELETE等方法不使用查询参数
	return "/v5/inout/authorization/delete"

}

// Method 返回HTTP方法
func (r *AuthorizationDeleteReq) Method() string {
	return "DELETE"
}

// Body 返回请求体
func (r *AuthorizationDeleteReq) Body() []byte {
	// POST/PUT/DELETE等方法将参数作为JSON body发送
	// 直接使用json.Marshal序列化结构体，会自动使用JSON tag
	jsonData, _ := json.Marshal(r)
	return jsonData

}

// ContentType 返回内容类型
func (r *AuthorizationDeleteReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AuthorizationDeleteReq) AuthRequired() bool {
	return true
}


// AuthorizationDeleteResp AuthorizationDelete响应
type AuthorizationDeleteResp struct {

}



