// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"
	"strconv"
)

// AuthorizationListReq AuthorizationList请求
type AuthorizationListReq struct {
	Page int64 `json:"page,omitempty"`
	PageSize int64 `json:"pageSize,omitempty"`
	Granter int64 `json:"granter,omitempty"`
	Grantee int64 `json:"grantee,omitempty"`
	GroupId int64 `json:"groupId,omitempty"`

}

// Api 返回API路径
func (r *AuthorizationListReq) Api() string {
	params := url.Values{}
	if r.Page > 0 {
		params.Add("page", strconv.FormatInt(r.Page, 10))
	}
	if r.PageSize > 0 {
		params.Add("pageSize", strconv.FormatInt(r.PageSize, 10))
	}
	if r.Granter > 0 {
		params.Add("granter", strconv.FormatInt(r.Granter, 10))
	}
	if r.Grantee > 0 {
		params.Add("grantee", strconv.FormatInt(r.Grantee, 10))
	}
	if r.GroupId > 0 {
		params.Add("groupId", strconv.FormatInt(r.GroupId, 10))
	}
	return fmt.Sprintf("/v5/inout/authorization/list?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *AuthorizationListReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *AuthorizationListReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *AuthorizationListReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AuthorizationListReq) AuthRequired() bool {
	return true
}


// AuthorizationListResp AuthorizationList响应
type AuthorizationListResp struct {
	List []*ListData `json:"list,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`

}



// ListData ListData
type ListData struct {
	Id int64 `json:"id,omitempty"`
	Granter int64 `json:"granter,omitempty"`
	Grantee int64 `json:"grantee,omitempty"`
	GroupId int64 `json:"groupId,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`

}

// Params 将ListData转换为url.Values
func (p ListData) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Id > 0 {
		params.Add(prefix+"id", strconv.FormatInt(p.Id, 10))
	}
	if p.Granter > 0 {
		params.Add(prefix+"granter", strconv.FormatInt(p.Granter, 10))
	}
	if p.Grantee > 0 {
		params.Add(prefix+"grantee", strconv.FormatInt(p.Grantee, 10))
	}
	if p.GroupId > 0 {
		params.Add(prefix+"groupId", strconv.FormatInt(p.GroupId, 10))
	}
	if p.CreatedAt != "" {
		params.Add(prefix+"createdAt", p.CreatedAt)
	}
	if p.UpdatedAt != "" {
		params.Add(prefix+"updatedAt", p.UpdatedAt)
	}
	return params
}


// Pagination Pagination
type Pagination struct {
	Page int64 `json:"page,omitempty"`
	PageSize int64 `json:"pageSize,omitempty"`
	Total int64 `json:"total,omitempty"`
	Pages int64 `json:"pages,omitempty"`

}

// Params 将Pagination转换为url.Values
func (p Pagination) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Page > 0 {
		params.Add(prefix+"page", strconv.FormatInt(p.Page, 10))
	}
	if p.PageSize > 0 {
		params.Add(prefix+"pageSize", strconv.FormatInt(p.PageSize, 10))
	}
	if p.Total > 0 {
		params.Add(prefix+"total", strconv.FormatInt(p.Total, 10))
	}
	if p.Pages > 0 {
		params.Add(prefix+"pages", strconv.FormatInt(p.Pages, 10))
	}
	return params
}


