// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"
	"github.com/piaofutong/odas-sdk/odas/request/common"
	"strconv"
)

// GroupListReq GroupList请求
type GroupListReq struct {
	Page common.Page `json:"page,omitempty"`
	Sid int64 `json:"sid,omitempty"`
	Owner bool `json:"owner,omitempty"`

}

// Api 返回API路径
func (r *GroupListReq) Api() string {
	params := url.Values{}
	for key, values := range r.Page.Params("page.") {
		for _, value := range values {
			params.Add(key, value)
		}
	}
	if r.Sid > 0 {
		params.Add("sid", strconv.FormatInt(r.Sid, 10))
	}
	if r.Owner {
		params.Add("owner", "true")
	}
	return fmt.Sprintf("/v5/inout/group/list?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *GroupListReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *GroupListReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *GroupListReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *GroupListReq) AuthRequired() bool {
	return true
}


// GroupListResp GroupList响应
type GroupListResp struct {
	Page common.Pagination `json:"page,omitempty"`
	List []*GroupGetResponse `json:"list,omitempty"`

}



// GroupGetResponse GroupGet响应
type GroupGetResponse struct {
	Id int64 `json:"id,omitempty"`
	Sid int64 `json:"sid,omitempty"`
	SerialNo string `json:"serialNo,omitempty"`
	Name string `json:"name,omitempty"`
	Gates []string `json:"gates,omitempty"`
	Capacity int64 `json:"capacity,omitempty"`
	UpperLimit int64 `json:"upperLimit,omitempty"`
	Config []*GroupConfig `json:"config,omitempty"`
	ExtConfig GroupExtConfig `json:"extConfig,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`

}

// Params 将GroupGetResponse转换为url.Values
func (p GroupGetResponse) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Id > 0 {
		params.Add(prefix+"id", strconv.FormatInt(p.Id, 10))
	}
	if p.Sid > 0 {
		params.Add(prefix+"sid", strconv.FormatInt(p.Sid, 10))
	}
	if p.SerialNo != "" {
		params.Add(prefix+"serialNo", p.SerialNo)
	}
	if p.Name != "" {
		params.Add(prefix+"name", p.Name)
	}
	if len(p.Gates) > 0 {
		for _, item := range p.Gates {
		params.Add(prefix+"gates", item)
	}
	}
	if p.Capacity > 0 {
		params.Add(prefix+"capacity", strconv.FormatInt(p.Capacity, 10))
	}
	if p.UpperLimit > 0 {
		params.Add(prefix+"upperLimit", strconv.FormatInt(p.UpperLimit, 10))
	}
	if len(p.Config) > 0 {
		for _, item := range p.Config {
		params.Add(prefix+"config", fmt.Sprintf("%v", item))
	}
	}
	for key, values := range p.ExtConfig.Params(prefix+"extConfig.") {
		for _, value := range values {
			params.Add(key, value)
		}
	}
	if p.CreatedAt != "" {
		params.Add(prefix+"createdAt", p.CreatedAt)
	}
	if p.UpdatedAt != "" {
		params.Add(prefix+"updatedAt", p.UpdatedAt)
	}
	return params
}


// GroupConfig GroupConfig
type GroupConfig struct {
	Label string `json:"label,omitempty"`
	Min int64 `json:"min,omitempty"`
	Max int64 `json:"max,omitempty"`
	Color string `json:"color,omitempty"`

}

// Params 将GroupConfig转换为url.Values
func (p GroupConfig) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Label != "" {
		params.Add(prefix+"label", p.Label)
	}
	if p.Min > 0 {
		params.Add(prefix+"min", strconv.FormatInt(p.Min, 10))
	}
	if p.Max > 0 {
		params.Add(prefix+"max", strconv.FormatInt(p.Max, 10))
	}
	if p.Color != "" {
		params.Add(prefix+"color", p.Color)
	}
	return params
}


// GroupExtConfig GroupExtConfig
type GroupExtConfig struct {
	ContainsEmployee bool `json:"containsEmployee,omitempty"`

}

// Params 将GroupExtConfig转换为url.Values
func (p GroupExtConfig) Params(prefix string) url.Values {
	params := url.Values{}
	if p.ContainsEmployee {
		params.Add(prefix+"containsEmployee", strconv.FormatBool(p.ContainsEmployee))
	}
	return params
}


