// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"
	"strconv"
)

// GroupGetReq GroupGet请求
type GroupGetReq struct {
	Id int64 `json:"id,omitempty"`

}

// Api 返回API路径
func (r *GroupGetReq) Api() string {
	params := url.Values{}
	if r.Id > 0 {
		params.Add("id", strconv.FormatInt(r.Id, 10))
	}
	return fmt.Sprintf("/v5/inout/group/get?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *GroupGetReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *GroupGetReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *GroupGetReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *GroupGetReq) AuthRequired() bool {
	return true
}


// GroupGetResp GroupGet响应
type GroupGetResp struct {
	Id int64 `json:"id,omitempty"`
	Sid int64 `json:"sid,omitempty"`
	SerialNo string `json:"serialNo,omitempty"`
	Name string `json:"name,omitempty"`
	Gates []string `json:"gates,omitempty"`
	Capacity int64 `json:"capacity,omitempty"`
	UpperLimit int64 `json:"upperLimit,omitempty"`
	Config []*GroupConfig `json:"config,omitempty"`
	ExtConfig GroupExtConfig `json:"extConfig,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`

}



