// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"encoding/json"
)

// AmendmentSaveReq AmendmentSave请求
type AmendmentSaveReq struct {
	Id int64 `json:"id,omitempty"`
	Gid int64 `json:"gid,omitempty"`
	Switch *int64 `json:"switch,omitempty"`
	Type int64 `json:"type,omitempty"`
	InPlus *int64 `json:"inPlus,omitempty"`
	OutPlus *int64 `json:"outPlus,omitempty"`
	InCoefficient float32 `json:"inCoefficient,omitempty"`
	OutCoefficient float32 `json:"outCoefficient,omitempty"`

}

// Api 返回API路径
func (r *AmendmentSaveReq) Api() string {
	// POST/PUT/DELETE等方法不使用查询参数
	return "/v5/inout/amendment/save"

}

// Method 返回HTTP方法
func (r *AmendmentSaveReq) Method() string {
	return "POST"
}

// Body 返回请求体
func (r *AmendmentSaveReq) Body() []byte {
	// POST/PUT/DELETE等方法将参数作为JSON body发送
	// 直接使用json.Marshal序列化结构体，会自动使用JSON tag
	jsonData, _ := json.Marshal(r)
	return jsonData

}

// ContentType 返回内容类型
func (r *AmendmentSaveReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AmendmentSaveReq) AuthRequired() bool {
	return true
}


// AmendmentSaveResp AmendmentSave响应
type AmendmentSaveResp struct {

}



