// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"
	"github.com/piaofutong/odas-sdk/odas/request/common"
	"strconv"
)

// SummaryByGroupReq SummaryByGroup请求
type SummaryByGroupReq struct {
	Request common.PassedTimeSpanRequest `json:"request,omitempty"`
	Gid []int `json:"gid,omitempty"`
	Amend *AmendConfig `json:"amend,omitempty"`

}

// Api 返回API路径
func (r *SummaryByGroupReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	if len(r.Gid) > 0 {
		for _, id := range r.Gid {
			params.Add("gid", strconv.Itoa(id))
		}
	}
	if r.Amend != nil {
		for key, values := range r.Amend.Params("amend.") {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}
	return fmt.Sprintf("/v5/inout/stat/g-group/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *SummaryByGroupReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *SummaryByGroupReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *SummaryByGroupReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *SummaryByGroupReq) AuthRequired() bool {
	return true
}


// SummaryByGroupResp SummaryByGroup响应
type SummaryByGroupResp struct {
	Total SummaryTotal `json:"total,omitempty"`
	List []*SummaryByGroupHourList `json:"list,omitempty"`

}



// SummaryByGroupHourList SummaryByGroupHourList
type SummaryByGroupHourList struct {
	Gid int `json:"gid,omitempty"`
	Name string `json:"name,omitempty"`
	Summary Summary `json:"summary,omitempty"`

}

// Params 将SummaryByGroupHourList转换为url.Values
func (p SummaryByGroupHourList) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Gid > 0 {
		params.Add(prefix+"gid", strconv.Itoa(p.Gid))
	}
	if p.Name != "" {
		params.Add(prefix+"name", p.Name)
	}
	for key, values := range p.Summary.Params(prefix+"summary.") {
		for _, value := range values {
			params.Add(key, value)
		}
	}
	return params
}


