// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"encoding/json"
)

// AmendmentDeleteReq  删除客流优化请求
type AmendmentDeleteReq struct {
	Id int64 `json:"id,omitempty"` // 客流优化ID
}

// Api 返回API路径
func (r *AmendmentDeleteReq) Api() string {
	// POST/PUT/DELETE等方法不使用查询参数
	return "/v5/inout/amendment/delete"

}

// Method 返回HTTP方法
func (r *AmendmentDeleteReq) Method() string {
	return "DELETE"
}

// Body 返回请求体
func (r *AmendmentDeleteReq) Body() []byte {
	// POST/PUT/DELETE等方法将参数作为JSON body发送
	// 直接使用json.Marshal序列化结构体，会自动使用JSON tag
	jsonData, _ := json.Marshal(r)
	return jsonData

}

// ContentType 返回内容类型
func (r *AmendmentDeleteReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AmendmentDeleteReq) AuthRequired() bool {
	return true
}

// AmendmentDeleteResp  删除客流优化响应
type AmendmentDeleteResp struct {
}
