// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"
	"strconv"
)

// AmendmentGetReq  获取客流优化请求
type AmendmentGetReq struct {
	Gid int64 `json:"gid,omitempty"` // 统计组id
}

// Api 返回API路径
func (r *AmendmentGetReq) Api() string {
	params := url.Values{}
	if r.Gid > 0 {
		params.Add("gid", strconv.FormatInt(r.Gid, 10))
	}
	return fmt.Sprintf("/v5/inout/amendment/get?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *AmendmentGetReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *AmendmentGetReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *AmendmentGetReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AmendmentGetReq) AuthRequired() bool {
	return true
}

// AmendmentGetResp  获取客流优化响应
type AmendmentGetResp struct {
	Id             int64   `json:"id,omitempty"`             // 客流优化ID
	Gid            int64   `json:"gid,omitempty"`            // 统计组id
	Switch         int64   `json:"switch,omitempty"`         // 客流优化开关：0 - 关闭，1-开启
	Type           int64   `json:"type,omitempty"`           // 客流优化方式：0 - 加减，1-系数
	InPlus         int64   `json:"inPlus,omitempty"`         // 入园加减数，例如：加50表示为50，减50表示为-50
	OutPlus        int64   `json:"outPlus,omitempty"`        // 出园加减数，例如：加50表示为50，减50表示为-50
	InCoefficient  float32 `json:"inCoefficient,omitempty"`  // 入园系数
	OutCoefficient float32 `json:"outCoefficient,omitempty"` // 出园系数
	DownTime       string  `json:"downTime,omitempty"`       // 下线时间
	CreatedAt      string  `json:"createdAt,omitempty"`      // 创建时间
	UpdatedAt      string  `json:"updatedAt,omitempty"`      // 最后更新时间

}
