// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"encoding/json"
)

// AuthorizationUpdateReq  更新授权请求
type AuthorizationUpdateReq struct {
	Id      int64 `json:"id,omitempty"`      // 出入园统计组授权ID
	GroupId int64 `json:"groupId,omitempty"` // 出入园统计组id
}

// Api 返回API路径
func (r *AuthorizationUpdateReq) Api() string {
	// POST/PUT/DELETE等方法不使用查询参数
	return "/v5/inout/authorization/update"

}

// Method 返回HTTP方法
func (r *AuthorizationUpdateReq) Method() string {
	return "PUT"
}

// Body 返回请求体
func (r *AuthorizationUpdateReq) Body() []byte {
	// POST/PUT/DELETE等方法将参数作为JSON body发送
	// 直接使用json.Marshal序列化结构体，会自动使用JSON tag
	jsonData, _ := json.Marshal(r)
	return jsonData

}

// ContentType 返回内容类型
func (r *AuthorizationUpdateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AuthorizationUpdateReq) AuthRequired() bool {
	return true
}

// AuthorizationUpdateResp  更新授权响应
type AuthorizationUpdateResp struct {
}
