// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"encoding/json"
)

// AuthorizationCreateReq  创建授权请求
type AuthorizationCreateReq struct {
	Granter int64 `json:"granter,omitempty"` // 授权人id
	Grantee int64 `json:"grantee,omitempty"` // 被授权人id
	GroupId int64 `json:"groupId,omitempty"` // 出入园统计组id
}

// Api 返回API路径
func (r *AuthorizationCreateReq) Api() string {
	// POST/PUT/DELETE等方法不使用查询参数
	return "/v5/inout/authorization/create"

}

// Method 返回HTTP方法
func (r *AuthorizationCreateReq) Method() string {
	return "POST"
}

// Body 返回请求体
func (r *AuthorizationCreateReq) Body() []byte {
	// POST/PUT/DELETE等方法将参数作为JSON body发送
	// 直接使用json.Marshal序列化结构体，会自动使用JSON tag
	jsonData, _ := json.Marshal(r)
	return jsonData

}

// ContentType 返回内容类型
func (r *AuthorizationCreateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AuthorizationCreateReq) AuthRequired() bool {
	return true
}

// AuthorizationCreateResp  创建授权响应
type AuthorizationCreateResp struct {
}
