// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"
	"strconv"
)

// GroupGetReq  获取统计组请求
type GroupGetReq struct {
	Id int64 `json:"id,omitempty"` // 出入园统计组ID
}

// Api 返回API路径
func (r *GroupGetReq) Api() string {
	params := url.Values{}
	if r.Id > 0 {
		params.Add("id", strconv.FormatInt(r.Id, 10))
	}
	return fmt.Sprintf("/v5/inout/group/get?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *GroupGetReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *GroupGetReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *GroupGetReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *GroupGetReq) AuthRequired() bool {
	return true
}

// GroupGetResp  获取统计组响应
type GroupGetResp struct {
	Id         int64          `json:"id,omitempty"`         // 出入园统计组ID
	Sid        int64          `json:"sid,omitempty"`        // 景区id
	SerialNo   string         `json:"serialNo,omitempty"`   // 统计组序列号
	Name       string         `json:"name,omitempty"`       // 统计组名称
	Gates      []string       `json:"gates,omitempty"`      // 闸机key列表， 例如["a","b"]
	Capacity   int64          `json:"capacity,omitempty"`   // 瞬时承载量
	UpperLimit int64          `json:"upperLimit,omitempty"` // 上限
	Config     []*GroupConfig `json:"config,omitempty"`     // 客流配置
	ExtConfig  GroupExtConfig `json:"extConfig,omitempty"`  // 出入园统计组扩展配置
	CreatedAt  string         `json:"createdAt,omitempty"`  // 创建时间
	UpdatedAt  string         `json:"updatedAt,omitempty"`  // 最后更新时间

}
