// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// GroupGroupListReq 统计组列表请求参数
type GroupGroupListReq struct {
	Sid   int64       `json:"sid"`   // 景区ID
	Owner bool        `json:"owner"` // 是否只包含自己创建的统计组
	Page  *types.Page `json:"page"`  // 分页信息
}

// Api 返回API路径
func (r *GroupGroupListReq) Api() string {
	params := url.Values{}
	if r.Sid > 0 {
		params.Add("sid", strconv.FormatInt(r.Sid, 10))
	}
	if r.Owner {
		params.Add("owner", "true")
	}
	if r.Page != nil {
		for key, values := range r.Page.Params("page.") {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}
	return fmt.Sprintf("/v5/inout/group/list?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *GroupGroupListReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *GroupGroupListReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *GroupGroupListReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *GroupGroupListReq) AuthRequired() bool {
	return true
}

// GroupGroupListResp 统计组列表响应
type GroupGroupListResp struct {
	Page *types.Pagination  `json:"page"` // 分页信息
	List []GroupGetResponse `json:"list"` // 统计组列表
}

// Page 分页参数
type Page struct {
	Page     int64 `json:"page"`     // 页码
	PageSize int64 `json:"pageSize"` // 每页大小
}

// Params 将Page转换为url.Values
func (p Page) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Page > 0 {
		params.Add(prefix+"page", strconv.FormatInt(p.Page, 10))
	}
	if p.PageSize > 0 {
		params.Add(prefix+"pageSize", strconv.FormatInt(p.PageSize, 10))
	}
	return params
}

// Pagination Common structures
type Pagination struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
	Total    int64 `json:"total"`
	Pages    int64 `json:"pages"`
}

// GroupGetResponse 统计组详情响应
type GroupGetResponse struct {
	Id         int64           `json:"id"`         // 出入园统计组ID
	Sid        int64           `json:"sid"`        // 景区ID
	SerialNo   string          `json:"serialNo"`   // 统计组序列号
	Name       string          `json:"name"`       // 统计组名称
	Gates      []string        `json:"gates"`      // 闸机key列表，例如["a","b"]
	Capacity   int64           `json:"capacity"`   // 瞬时承载量
	UpperLimit int64           `json:"upperLimit"` // 上限
	Config     []GroupConfig   `json:"config"`     // 客流配置
	CreatedAt  string          `json:"createdAt"`  // 创建时间
	UpdatedAt  string          `json:"updatedAt"`  // 最后更新时间
	ExtConfig  *GroupExtConfig `json:"extConfig"`  // 出入园统计组扩展配置
}

// GroupConfig 统计组客流配置
type GroupConfig struct {
	Label string `json:"label"` // 显示名称
	Min   int64  `json:"min"`   // 客流配置匹配最小客流比例（百分比）
	Max   int64  `json:"max"`   // 客流配置匹配最大客流比例（百分比）
	Color string `json:"color"` // 显示颜色
}

// GroupExtConfig 统计组扩展配置
type GroupExtConfig struct {
	ExcludeEmployee bool `json:"excludeEmployee"` // 出入园统计数据是否排除刷员工卡的数量
}
