// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"encoding/json"
)

// GroupUpdateReq  更新统计组请求
type GroupUpdateReq struct {
	Id         int64          `json:"id,omitempty"`         // 景区id
	Name       string         `json:"name,omitempty"`       // 统计组名称
	Gates      []string       `json:"gates,omitempty"`      // 闸机key列表， 例如["a","b"]
	Capacity   int64          `json:"capacity,omitempty"`   // 瞬时承载量
	UpperLimit int64          `json:"upperLimit,omitempty"` // 上限
	Config     []*GroupConfig `json:"config,omitempty"`     // 客流配置
	ExtConfig  GroupExtConfig `json:"extConfig,omitempty"`  // 出入园统计组扩展配置
}

// Api 返回API路径
func (r *GroupUpdateReq) Api() string {
	// POST/PUT/DELETE等方法不使用查询参数
	return "/v5/inout/group/update"

}

// Method 返回HTTP方法
func (r *GroupUpdateReq) Method() string {
	return "PUT"
}

// Body 返回请求体
func (r *GroupUpdateReq) Body() []byte {
	// POST/PUT/DELETE等方法将参数作为JSON body发送
	// 直接使用json.Marshal序列化结构体，会自动使用JSON tag
	jsonData, _ := json.Marshal(r)
	return jsonData

}

// ContentType 返回内容类型
func (r *GroupUpdateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *GroupUpdateReq) AuthRequired() bool {
	return true
}

// GroupUpdateResp  更新统计组响应
type GroupUpdateResp struct {
}
