// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"encoding/json"
)

// GroupCreateReq  创建统计组请求
type GroupCreateReq struct {
	Sid        int            `json:"sid,omitempty"`        // 景区id
	Name       string         `json:"name,omitempty"`       // 统计组名称
	Gates      []string       `json:"gates,omitempty"`      // 闸机key列表， 例如["a","b"]
	Capacity   int64          `json:"capacity,omitempty"`   // 瞬时承载量
	UpperLimit int64          `json:"upperLimit,omitempty"` // 上限
	ExtConfig  GroupExtConfig `json:"extConfig,omitempty"`  // 出入园统计组扩展配置
	Config     []*GroupConfig `json:"config,omitempty"`     // 客流配置
}

// Api 返回API路径
func (r *GroupCreateReq) Api() string {
	// POST/PUT/DELETE等方法不使用查询参数
	return "/v5/inout/group/create"

}

// Method 返回HTTP方法
func (r *GroupCreateReq) Method() string {
	return "POST"
}

// Body 返回请求体
func (r *GroupCreateReq) Body() []byte {
	// POST/PUT/DELETE等方法将参数作为JSON body发送
	// 直接使用json.Marshal序列化结构体，会自动使用JSON tag
	jsonData, _ := json.Marshal(r)
	return jsonData

}

// ContentType 返回内容类型
func (r *GroupCreateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *GroupCreateReq) AuthRequired() bool {
	return true
}

// GroupCreateResp  创建统计组响应
type GroupCreateResp struct {
	Id       int64  `json:"id,omitempty"`       // 出入园统计组ID
	SerialNo string `json:"serialNo,omitempty"` // 统计组序列号

}
