// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"

	strconv "strconv"
)

// GroupGroupGetReq 获取统计组详情请求参数
type GroupGroupGetReq struct {
	Id  int64 `json:"id" validate:"required"` // 出入园统计组ID
	Sid int64 `json:"sid"`                    // 景区ID
}

// Api 返回API路径
func (r *GroupGroupGetReq) Api() string {
	params := url.Values{}
	if r.Id > 0 {
		params.Add("id", strconv.FormatInt(r.Id, 10))
	}
	if r.Sid > 0 {
		params.Add("sid", strconv.FormatInt(r.Sid, 10))
	}
	return fmt.Sprintf("/v5/inout/group/get?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *GroupGroupGetReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *GroupGroupGetReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *GroupGroupGetReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *GroupGroupGetReq) AuthRequired() bool {
	return true
}

// GroupGroupGetResp 统计组详情响应
type GroupGroupGetResp struct {
	Id         int64           `json:"id"`         // 出入园统计组ID
	Sid        int64           `json:"sid"`        // 景区ID
	SerialNo   string          `json:"serialNo"`   // 统计组序列号
	Name       string          `json:"name"`       // 统计组名称
	Gates      []string        `json:"gates"`      // 闸机key列表，例如["a","b"]
	Capacity   int64           `json:"capacity"`   // 瞬时承载量
	UpperLimit int64           `json:"upperLimit"` // 上限
	Config     []GroupConfig   `json:"config"`     // 客流配置
	CreatedAt  string          `json:"createdAt"`  // 创建时间
	UpdatedAt  string          `json:"updatedAt"`  // 最后更新时间
	ExtConfig  *GroupExtConfig `json:"extConfig"`  // 出入园统计组扩展配置
}
