// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"encoding/json"
)

// AmendmentSaveReq  保存客流优化请求
type AmendmentSaveReq struct {
	Id             int64   `json:"id,omitempty"`             // 客流优化ID
	Gid            int64   `json:"gid,omitempty"`            // 统计组id
	Switch         *int64  `json:"switch,omitempty"`         // 客流优化开关：0 - 关闭，1-开启
	Type           int64   `json:"type,omitempty"`           // 客流优化方式：0 - 加减，1-系数
	InPlus         *int64  `json:"inPlus,omitempty"`         // 入园加减数，例如：加50表示为50，减50表示为-50
	OutPlus        *int64  `json:"outPlus,omitempty"`        // 出园加减数，例如：加50表示为50，减50表示为-50
	InCoefficient  float32 `json:"inCoefficient,omitempty"`  // 入园系数
	OutCoefficient float32 `json:"outCoefficient,omitempty"` // 出园系数
}

// Api 返回API路径
func (r *AmendmentSaveReq) Api() string {
	// POST/PUT/DELETE等方法不使用查询参数
	return "/v5/inout/amendment/save"

}

// Method 返回HTTP方法
func (r *AmendmentSaveReq) Method() string {
	return "POST"
}

// Body 返回请求体
func (r *AmendmentSaveReq) Body() []byte {
	// POST/PUT/DELETE等方法将参数作为JSON body发送
	// 直接使用json.Marshal序列化结构体，会自动使用JSON tag
	jsonData, _ := json.Marshal(r)
	return jsonData

}

// ContentType 返回内容类型
func (r *AmendmentSaveReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *AmendmentSaveReq) AuthRequired() bool {
	return true
}

// AmendmentSaveResp  保存客流优化响应
type AmendmentSaveResp struct {
}
