// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
	time "time"
)

// StatSummaryReq 按时间维度查询出入园数据请求参数
type StatSummaryReq struct {
	Request *types.PassedTimeSpanRequest `json:"request"`                 // 时间范围请求参数
	Gid     []int64                      `json:"gid" validate:"required"` // 出入园统计组ID列表
	NoAmend bool                         `json:"noAmend"`                 // 是否返回优化客流修订后的数据：true-返回原始数据，false-返回修订后数据
}

// Api 返回API路径
func (r *StatSummaryReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if len(r.Gid) > 0 {
		for _, id := range r.Gid {
			params.Add("gid", strconv.FormatInt(id, 10))
		}
	}
	if r.NoAmend {
		params.Add("noAmend", "true")
	}
	return fmt.Sprintf("/v5/inout/stat/g-hour/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *StatSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *StatSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *StatSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *StatSummaryReq) AuthRequired() bool {
	return true
}

// StatSummaryResp 按时间维度查询出入园数据响应结果
type StatSummaryResp struct {
	Total *StatSummary            `json:"total"` // 汇总统计数据
	List  []StatSummaryByHourList `json:"list"`  // 详细统计数据列表
}

// PassedTimeSpanRequest 时间范围请求参数
type PassedTimeSpanRequest struct {
	Sid      []int64        `json:"sid"`                       // 景区ID列表
	Start    time.Time      `json:"start" validate:"required"` // 开始时间: YYY-MM-DD; 如: 2021-01-01
	End      time.Time      `json:"end" validate:"required"`   // 结束时间: YYY-MM-DD; 如: 2021-01-01
	DateType types.DateType `json:"dateType"`                  // 日期类型(默认 0): 0 (DAILY)按日期范围; 1 (MONTHLY)只处理日期中的年和月然后整月查询; 2 (YEARLY)整年查询
}

// Params 将PassedTimeSpanRequest转换为url.Values
func (p PassedTimeSpanRequest) Params(prefix string) url.Values {
	params := url.Values{}
	if len(p.Sid) > 0 {
		for _, item := range p.Sid {
			params.Add(prefix+"sid", strconv.FormatInt(item, 10))
		}
	}
	if !p.Start.IsZero() {
		params.Add(prefix+"start", p.Start.Format("2006-01-02 15:04:05"))
	}
	if !p.End.IsZero() {
		params.Add(prefix+"end", p.End.Format("2006-01-02 15:04:05"))
	}
	if p.DateType > 0 {
		params.Add(prefix+"dateType", strconv.FormatInt(int64(p.DateType), 10))
	}
	return params
}

// StatSummary 闸机出入园汇总数据
type StatSummary struct {
	In       int64 `json:"in"`       // 入园人数
	Out      int64 `json:"out"`      // 出园人数
	Hold     int64 `json:"hold"`     // 在园人数
	Employee int64 `json:"employee"` // 员工卡入园人数
}

// StatSummaryByHourList 按小时维度出入园统计数据
type StatSummaryByHourList struct {
	Hour     int64 `json:"hour"`     // 小时，范围：0-23
	In       int64 `json:"in"`       // 入园人数
	Out      int64 `json:"out"`      // 出园人数
	Hold     int64 `json:"hold"`     // 在园人数
	Employee int64 `json:"employee"` // 员工卡入园人数
}
