// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// StatSummaryByDateReq 按日期维度查询出入园数据请求参数
type StatSummaryByDateReq struct {
	Request *types.PassedTimeSpanRequest `json:"request"`                 // 时间范围请求参数
	Gid     []int64                      `json:"gid" validate:"required"` // 出入园统计组ID列表
	NoAmend bool                         `json:"noAmend"`                 // 是否返回优化客流修订后的数据：true-返回原始数据，false-返回修订后数据
}

// Api 返回API路径
func (r *StatSummaryByDateReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if len(r.Gid) > 0 {
		for _, id := range r.Gid {
			params.Add("gid", strconv.FormatInt(id, 10))
		}
	}
	if r.NoAmend {
		params.Add("noAmend", "true")
	}
	return fmt.Sprintf("/v5/inout/stat/g-date/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *StatSummaryByDateReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *StatSummaryByDateReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *StatSummaryByDateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *StatSummaryByDateReq) AuthRequired() bool {
	return true
}

// StatSummaryByDateResp 按日期维度查询出入园数据响应结果
type StatSummaryByDateResp struct {
	Total *StatSummary        `json:"total"` // 汇总统计数据
	List  []SummaryByDateList `json:"list"`  // 详细统计数据列表
}

// SummaryByDateList 出入园统计详情数据
type SummaryByDateList struct {
	Date  string                  `json:"date"`  // 时间，格式根据查询维度而定
	Total *StatSummary            `json:"total"` // 汇总统计数据
	List  []StatSummaryByHourList `json:"list"`  // 详细统计数据列表
}
