// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"net/url"

	strconv "strconv"
)

// StatTodaySummaryReq
type StatTodaySummaryReq struct {
	Sid     []int64 `json:"sid"`     // 供应商ID
	Gid     []int64 `json:"gid"`     // 出入园统计组ID
	NoAmend bool    `json:"noAmend"` // 是否返回优化客流修订后的数据：true-返回原始数据，false-返回修订后数据
}

// Api 返回API路径
func (r *StatTodaySummaryReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Gid) > 0 {
		for _, id := range r.Gid {
			params.Add("gid", strconv.FormatInt(id, 10))
		}
	}
	if r.NoAmend {
		params.Add("noAmend", "true")
	}
	return fmt.Sprintf("/v5/inout/stat/g-hour/today-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *StatTodaySummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *StatTodaySummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *StatTodaySummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *StatTodaySummaryReq) AuthRequired() bool {
	return true
}

// StatTodaySummaryResp 按时间维度查询出入园数据响应结果
type StatTodaySummaryResp struct {
	Total *StatSummary            `json:"total"` // 汇总统计数据
	List  []StatSummaryByHourList `json:"list"`  // 详细统计数据列表
}
