// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package inout

import (
	"fmt"
	"github.com/piaofutong/odas-sdk/odas/common"
	"net/url"
	"strconv"
)

// SummaryByDateReq SummaryByGroupDateRequest 按日期统计请求
type SummaryByDateReq struct {
	Request common.PassedTimeSpanRequest `json:"request,omitempty"`
	Gid     []int                        `json:"gid,omitempty"`   // 出入园统计组id
	Amend   *AmendConfig                 `json:"amend,omitempty"` // 出入园数据优化选项
}

// Api 返回API路径
func (r *SummaryByDateReq) Api() string {
	params := url.Values{}

	requestParams := r.Request.Params("")
	for key, values := range requestParams {
		for _, value := range values {
			params.Add(key, value)
		}
	}

	if len(r.Gid) > 0 {
		for _, id := range r.Gid {
			params.Add("gid", strconv.Itoa(id))
		}
	}
	if r.Amend != nil {
		for key, values := range r.Amend.Params("amend.") {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}
	return fmt.Sprintf("/v5/inout/stat/g-date/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *SummaryByDateReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *SummaryByDateReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *SummaryByDateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *SummaryByDateReq) AuthRequired() bool {
	return true
}

// SummaryByDateResp SummaryByGroupDateResponse 按日期统计响应
type SummaryByDateResp struct {
	Total SummaryTotal         `json:"total,omitempty"`
	List  []*SummaryByDateList `json:"list,omitempty"`
}

// SummaryByDateList  统计列表数据
type SummaryByDateList struct {
	Date    string  `json:"date,omitempty"`    // 日期
	Summary Summary `json:"summary,omitempty"` // 统计指标详情

}

// Params 将SummaryByDateList转换为url.Values
func (p SummaryByDateList) Params(prefix string) url.Values {
	params := url.Values{}
	if p.Date != "" {
		params.Add(prefix+"date", p.Date)
	}
	for key, values := range p.Summary.Params(prefix + "summary.") {
		for _, value := range values {
			params.Add(key, value)
		}
	}
	return params
}

// Summary Total 统计汇总数据
type Summary struct {
	Total SummaryTotal         `json:"total,omitempty"`   // 统计指标
	List  []*SummaryByHourList `json:"summary,omitempty"` // 统计指标详情

}

// Params 将Summary转换为url.Values
func (p Summary) Params(prefix string) url.Values {
	params := url.Values{}
	for key, values := range p.Total.Params(prefix + "total.") {
		for _, value := range values {
			params.Add(key, value)
		}
	}
	if len(p.List) > 0 {
		for _, item := range p.List {
			params.Add(prefix+"summary", fmt.Sprintf("%v", item))
		}
	}
	return params
}
