// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"

	strconv "strconv"
	time "time"
)

// LvyunHotelRmOrderSummaryReq 酒店订单统计数据查询请求参数
type LvyunHotelRmOrderSummaryReq struct {
	Sid   []int64   `json:"sid"`   // 景区ID列表
	Start time.Time `json:"start"` // 开始时间
	End   time.Time `json:"end"`   // 结束时间
}

// Api 返回API路径
func (r *LvyunHotelRmOrderSummaryReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if !r.Start.IsZero() {
		params.Add("start", r.Start.Format("2006-01-02 15:04:05"))
	}
	if !r.End.IsZero() {
		params.Add("end", r.End.Format("2006-01-02 15:04:05"))
	}
	return fmt.Sprintf("/v5/s3rd/lvyun-hotel/rm-order-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *LvyunHotelRmOrderSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *LvyunHotelRmOrderSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *LvyunHotelRmOrderSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *LvyunHotelRmOrderSummaryReq) AuthRequired() bool {
	return true
}

// LvyunHotelRmOrderSummaryResp 酒店订单统计数据查询响应结果
type LvyunHotelRmOrderSummaryResp struct {
	Total *RmOrderSummary     `json:"total"` // 汇总订单统计数据
	List  []RmOrderReportList `json:"list"`  // 按日期详细订单统计数据列表
}

// RmOrderSummary 酒店订单统计汇总数据
type RmOrderSummary struct {
	BookingCount    int64 `json:"bookingCount"`    // 预订订单数
	BookingRoomNum  int64 `json:"bookingRoomNum"`  // 预订房间数
	BookingAdult    int64 `json:"bookingAdult"`    // 预订成人数
	BookingChildren int64 `json:"bookingChildren"` // 预订儿童数
	BookingPeople   int64 `json:"bookingPeople"`   // 预订总人数
	BookingCharge   int64 `json:"bookingCharge"`   // 预订应收金额
	BookingPay      int64 `json:"bookingPay"`      // 预订实收金额
	CheckInCount    int64 `json:"checkInCount"`    // 入住订单数
	CheckInRoomNum  int64 `json:"checkInRoomNum"`  // 入住房间数
	CheckInAdult    int64 `json:"checkInAdult"`    // 入住成人数
	CheckInChildren int64 `json:"checkInChildren"` // 入住儿童数
	CheckInPeople   int64 `json:"checkInPeople"`   // 入住总人数
	CheckInCharge   int64 `json:"checkInCharge"`   // 入住应收金额
	CheckInPay      int64 `json:"checkInPay"`      // 入住实收金额
}

// RmOrderReportList 按日期订单统计数据
type RmOrderReportList struct {
	Date    string          `json:"date"`    // 日期，格式：YYYY-MM-DD
	Summary *RmOrderSummary `json:"summary"` // 当日订单统计数据
}
