// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"

	strconv "strconv"
	time "time"
)

// LvyunHotelOccupancyReq 酒店入住人数查询请求参数
type LvyunHotelOccupancyReq struct {
	Sid   []int64   `json:"sid"`   // 景区ID列表
	Start time.Time `json:"start"` // 开始时间
	End   time.Time `json:"end"`   // 结束时间
}

// Api 返回API路径
func (r *LvyunHotelOccupancyReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if !r.Start.IsZero() {
		params.Add("start", r.Start.Format("2006-01-02 15:04:05"))
	}
	if !r.End.IsZero() {
		params.Add("end", r.End.Format("2006-01-02 15:04:05"))
	}
	return fmt.Sprintf("/v5/s3rd/lvyun-hotel/occupancy?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *LvyunHotelOccupancyReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *LvyunHotelOccupancyReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *LvyunHotelOccupancyReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *LvyunHotelOccupancyReq) AuthRequired() bool {
	return true
}

// LvyunHotelOccupancyResp 酒店入住人数查询响应结果
type LvyunHotelOccupancyResp struct {
	Occupancy int64 `json:"occupancy"` // 入住人数
}
