// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"

	strconv "strconv"
	time "time"
)

// LvyunHotelRmSaleSummaryByBindReq 按酒店维度销售指标数据查询请求参数
type LvyunHotelRmSaleSummaryByBindReq struct {
	Sid   []int64   `json:"sid"`   // 景区ID列表
	Start time.Time `json:"start"` // 开始时间
	End   time.Time `json:"end"`   // 结束时间
}

// Api 返回API路径
func (r *LvyunHotelRmSaleSummaryByBindReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if !r.Start.IsZero() {
		params.Add("start", r.Start.Format("2006-01-02 15:04:05"))
	}
	if !r.End.IsZero() {
		params.Add("end", r.End.Format("2006-01-02 15:04:05"))
	}
	return fmt.Sprintf("/v5/s3rd/lvyun-hotel/g-bind/rm-sale-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *LvyunHotelRmSaleSummaryByBindReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *LvyunHotelRmSaleSummaryByBindReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *LvyunHotelRmSaleSummaryByBindReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *LvyunHotelRmSaleSummaryByBindReq) AuthRequired() bool {
	return true
}

// LvyunHotelRmSaleSummaryByBindResp 按酒店维度销售指标数据查询响应结果
type LvyunHotelRmSaleSummaryByBindResp struct {
	Total *RmSaleSummary            `json:"total"` // 汇总销售指标数据
	List  []RmSaleSummaryByBindList `json:"list"`  // 按酒店详细销售指标数据列表
}

// RmSaleSummaryByBindList 按酒店销售指标数据
type RmSaleSummaryByBindList struct {
	BindId  int64          `json:"bindId"`  // 酒店绑定ID
	Name    string         `json:"name"`    // 酒店名称
	Summary *RmSaleSummary `json:"summary"` // 酒店销售指标数据
}
