// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"

	strconv "strconv"
	time "time"
)

// LvyunHotelRevenueSummaryByCodeCategoryReq 按预订来源分类收入统计数据查询请求参数
type LvyunHotelRevenueSummaryByCodeCategoryReq struct {
	Sid          []int64   `json:"sid"`          // 景区ID列表
	Start        time.Time `json:"start"`        // 开始时间
	End          time.Time `json:"end"`          // 结束时间
	CodeCategory []string  `json:"codeCategory"` // 预订来源分类代码列表
}

// Api 返回API路径
func (r *LvyunHotelRevenueSummaryByCodeCategoryReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if !r.Start.IsZero() {
		params.Add("start", r.Start.Format("2006-01-02 15:04:05"))
	}
	if !r.End.IsZero() {
		params.Add("end", r.End.Format("2006-01-02 15:04:05"))
	}
	if len(r.CodeCategory) > 0 {
		for _, id := range r.CodeCategory {
			params.Add("codeCategory", id)
		}
	}
	return fmt.Sprintf("/v5/s3rd/lvyun-hotel/g-code-category/revenue-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *LvyunHotelRevenueSummaryByCodeCategoryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *LvyunHotelRevenueSummaryByCodeCategoryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *LvyunHotelRevenueSummaryByCodeCategoryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *LvyunHotelRevenueSummaryByCodeCategoryReq) AuthRequired() bool {
	return true
}

// LvyunHotelRevenueSummaryByCodeCategoryResp 按预订来源分类收入统计数据查询响应结果
type LvyunHotelRevenueSummaryByCodeCategoryResp struct {
	Total *RevenueSummary                    `json:"total"` // 汇总收入统计数据
	List  []RevenueSummaryByCodeCategoryList `json:"list"`  // 按预订来源分类详细收入统计数据列表
}

// RevenueSummary 酒店收入统计汇总数据
type RevenueSummary struct {
	RevTotal    float64 `json:"revTotal"`    // 总收入
	RevRm       float64 `json:"revRm"`       // 客房收入
	RevFb       float64 `json:"revFb"`       // 餐饮收入
	RevMt       float64 `json:"revMt"`       // 会议收入
	RevEn       float64 `json:"revEn"`       // 娱乐收入
	RevSp       float64 `json:"revSp"`       // 水疗收入
	RevOt       float64 `json:"revOt"`       // 其他收入
	RoomsTotal  float64 `json:"roomsTotal"`  // 总房间数
	RoomsArr    float64 `json:"roomsArr"`    // 到店房间数
	RoomsDep    float64 `json:"roomsDep"`    // 离店房间数
	RoomsNoShow int64   `json:"roomsNoShow"` // 未到店房间数
	RoomsCxl    int64   `json:"roomsCxl"`    // 取消房间数
	People      int64   `json:"people"`      // 总人数
	PeopleArr   int64   `json:"peopleArr"`   // 到店人数
	PeopleDep   int64   `json:"peopleDep"`   // 离店人数
}

// RevenueSummaryByCodeCategoryList 按预订来源分类收入统计数据
type RevenueSummaryByCodeCategoryList struct {
	CodeCategory    string          `json:"codeCategory"`    // 预订来源分类代码
	CodeCategoryDes string          `json:"codeCategoryDes"` // 预订来源分类描述
	Summary         *RevenueSummary `json:"summary"`         // 该分类收入统计数据
}
