// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"

	strconv "strconv"
	time "time"
)

// LvyunHotelRmSaleSummaryReq 酒店销售指标数据查询请求参数
type LvyunHotelRmSaleSummaryReq struct {
	Sid   []int64   `json:"sid"`   // 景区ID列表
	Start time.Time `json:"start"` // 开始时间
	End   time.Time `json:"end"`   // 结束时间
}

// Api 返回API路径
func (r *LvyunHotelRmSaleSummaryReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if !r.Start.IsZero() {
		params.Add("start", r.Start.Format("2006-01-02 15:04:05"))
	}
	if !r.End.IsZero() {
		params.Add("end", r.End.Format("2006-01-02 15:04:05"))
	}
	return fmt.Sprintf("/v5/s3rd/lvyun-hotel/rm-sale-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *LvyunHotelRmSaleSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *LvyunHotelRmSaleSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *LvyunHotelRmSaleSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *LvyunHotelRmSaleSummaryReq) AuthRequired() bool {
	return true
}

// LvyunHotelRmSaleSummaryResp 酒店销售指标数据查询响应结果
type LvyunHotelRmSaleSummaryResp struct {
	Total *RmSaleSummary     `json:"total"` // 汇总销售指标数据
	List  []RmSaleReportList `json:"list"`  // 按日期详细销售指标数据列表
}

// RmSaleSummary 酒店销售指标汇总数据
type RmSaleSummary struct {
	RoomsTotal float64 `json:"roomsTotal"` // 总房间数
	RoomsOoo   float64 `json:"roomsOoo"`   // 维修房间数
	RoomsOs    float64 `json:"roomsOs"`    // 超售房间数
	RoomsHse   float64 `json:"roomsHse"`   // 自用房间数
	RoomsAvl   float64 `json:"roomsAvl"`   // 可售房间数
	RoomsVac   float64 `json:"roomsVac"`   // 空房间数
	SoldFit    float64 `json:"soldFit"`    // 散客已售房间数
	SoldGrp    float64 `json:"soldGrp"`    // 团队已售房间数
	SoldLong   float64 `json:"soldLong"`   // 长住已售房间数
	SoldEnt    float64 `json:"soldEnt"`    // 企业已售房间数
	RevFit     float64 `json:"revFit"`     // 散客收入
	RevGrp     float64 `json:"revGrp"`     // 团队收入
	RevLong    float64 `json:"revLong"`    // 长住收入
	PeopleFit  int64   `json:"peopleFit"`  // 散客人数
	PeopleGrp  int64   `json:"peopleGrp"`  // 团队人数
	PeopleLong int64   `json:"peopleLong"` // 长住人数
}

// RmSaleReportList 按日期销售指标数据
type RmSaleReportList struct {
	Date    string         `json:"date"`    // 日期，格式：YYYY-MM-DD
	Summary *RmSaleSummary `json:"summary"` // 当日销售指标数据
}
