// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"
	"strconv"
	"time"
)

// OccupancyReq  入住率请求
type OccupancyReq struct {
	Sid   []int64   `json:"sid,omitempty"`
	Start time.Time `json:"start,omitempty"`
	End   time.Time `json:"end,omitempty"`
}

// Api 返回API路径
func (r *OccupancyReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if !r.Start.IsZero() {
		params.Add("start", r.Start.Format("2006-01-02 15:04:05"))
	}
	if !r.End.IsZero() {
		params.Add("end", r.End.Format("2006-01-02 15:04:05"))
	}
	return fmt.Sprintf("/v5/s3rd/lvyun-hotel/occupancy?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *OccupancyReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *OccupancyReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *OccupancyReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *OccupancyReq) AuthRequired() bool {
	return true
}

// OccupancyResp  入住率响应
type OccupancyResp struct {
	Occupancy int64 `json:"occupancy,omitempty"`
}
