// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"

	strconv "strconv"
)

// ParkingSpaceReq 停车位信息查询请求参数
type ParkingSpaceReq struct {
	Sid []int64 `json:"sid"` // 景区ID列表
}

// Api 返回API路径
func (r *ParkingSpaceReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/s3rd/parking/space?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ParkingSpaceReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ParkingSpaceReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ParkingSpaceReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ParkingSpaceReq) AuthRequired() bool {
	return true
}

// ParkingSpaceResp 停车位信息查询响应结果
type ParkingSpaceResp struct {
	Summary *SpaceTotal `json:"summary"` // 停车位汇总信息
	List    []SpaceList `json:"list"`    // 停车场详细信息列表
}

// SpaceTotal 停车位汇总信息
type SpaceTotal struct {
	Total  int64 `json:"total"`  // 总停车位数
	Remain int64 `json:"remain"` // 剩余停车位数
	Used   int64 `json:"used"`   // 已使用停车位数
}

// SpaceList 停车场详细信息
type SpaceList struct {
	BindId int64  `json:"bindId"` // 停车场绑定ID
	Name   string `json:"name"`   // 停车场名称
	Total  int64  `json:"total"`  // 总停车位数
	Remain int64  `json:"remain"` // 剩余停车位数
	Used   int64  `json:"used"`   // 已使用停车位数
}
