// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"

	strconv "strconv"
	time "time"
)

// ParkingInoutSummaryByHourReq 按小时维度出入场数据查询请求参数
type ParkingInoutSummaryByHourReq struct {
	Sid     []int64   `json:"sid"`     // 景区ID列表
	Date    time.Time `json:"date"`    // 查询日期，不传获取当天
	Compare time.Time `json:"compare"` // 对比日期，有值时会返回对应日期的数据用作对比
}

// Api 返回API路径
func (r *ParkingInoutSummaryByHourReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if !r.Date.IsZero() {
		params.Add("date", r.Date.Format("2006-01-02 15:04:05"))
	}
	if !r.Compare.IsZero() {
		params.Add("compare", r.Compare.Format("2006-01-02 15:04:05"))
	}
	return fmt.Sprintf("/v5/s3rd/parking/g-hour/inout-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ParkingInoutSummaryByHourReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ParkingInoutSummaryByHourReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ParkingInoutSummaryByHourReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ParkingInoutSummaryByHourReq) AuthRequired() bool {
	return true
}

// ParkingInoutSummaryByHourResp 按小时维度出入场数据查询响应结果
type ParkingInoutSummaryByHourResp struct {
	Total        *InoutSummary            `json:"total"`        // 查询日期汇总数据
	CompareTotal *InoutSummary            `json:"compareTotal"` // 对比日期汇总数据
	List         []InoutSummaryByHourList `json:"list"`         // 按小时详细数据列表
}

// InoutSummary 出入场统计汇总数据
type InoutSummary struct {
	In    int64 `json:"in"`    // 入场车辆数
	Out   int64 `json:"out"`   // 出场车辆数
	Being int64 `json:"being"` // 在场车辆数
}

// InoutSummaryByHourList 按小时出入场统计数据
type InoutSummaryByHourList struct {
	Hour    int32         `json:"hour"`    // 小时数，范围：0-23
	Time    string        `json:"time"`    // 时间，格式：HH:00
	Summary *InoutSummary `json:"summary"` // 查询日期数据 - 如果是当天，不是24小时，只到当前小时
	Compare *InoutSummary `json:"compare"` // 对比日期数据 - 如果是当天，不是24小时，只到当前小时
}
