// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package s3rd

import (
	"fmt"
	"net/url"

	strconv "strconv"
	time "time"
)

// ParkingLocationInSummaryReq 按地区维度入场数据查询请求参数
type ParkingLocationInSummaryReq struct {
	Sid      []int64   `json:"sid" validate:"required"`      // 景区ID列表
	Start    time.Time `json:"start" validate:"required"`    // 开始时间
	End      time.Time `json:"end" validate:"required"`      // 结束时间
	Province string    `json:"province" validate:"required"` // 省份名称，用于筛选省内外数据
	Unknown  bool      `json:"unknown"`                      // 是否包含未知地区数据
	Limit    int64     `json:"limit"`                        // 返回数据条数限制
}

// Api 返回API路径
func (r *ParkingLocationInSummaryReq) Api() string {
	params := url.Values{}
	if len(r.Sid) > 0 {
		for _, id := range r.Sid {
			params.Add("sid", strconv.FormatInt(id, 10))
		}
	}
	if !r.Start.IsZero() {
		params.Add("start", r.Start.Format("2006-01-02 15:04:05"))
	}
	if !r.End.IsZero() {
		params.Add("end", r.End.Format("2006-01-02 15:04:05"))
	}
	if r.Province != "" {
		params.Add("province", r.Province)
	}
	if r.Unknown {
		params.Add("unknown", "true")
	}
	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	return fmt.Sprintf("/v5/s3rd/parking/location-in-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *ParkingLocationInSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *ParkingLocationInSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *ParkingLocationInSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *ParkingLocationInSummaryReq) AuthRequired() bool {
	return true
}

// ParkingLocationInSummaryResp 按地区维度入场数据查询响应结果
type ParkingLocationInSummaryResp struct {
	Summary      *LocationInSummaryTotal `json:"summary"`      // 地区入场数据汇总
	CityList     []LocationInSummaryList `json:"cityList"`     // 按城市详细数据列表
	ProvinceList []LocationInSummaryList `json:"provinceList"` // 按省份详细数据列表
}

// LocationInSummaryTotal 地区入场数据汇总信息
type LocationInSummaryTotal struct {
	Total           int64   `json:"total"`           // 总入场车辆数
	ProvinceTotal   int64   `json:"provinceTotal"`   // 省内入场车辆数
	ProvincePercent float64 `json:"provincePercent"` // 省内入场占比百分比
	CityTotal       int64   `json:"cityTotal"`       // 本市入场车辆数
	CityPercent     float64 `json:"cityPercent"`     // 本市入场占比百分比
}

// LocationInSummaryList 地区入场统计数据
type LocationInSummaryList struct {
	Location string  `json:"location"` // 地区名称（城市或省份）
	In       int64   `json:"in"`       // 入场车辆数
	Rate     float32 `json:"rate"`     // 占比百分比
}
