// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// FlowForecastTouristSummaryReq 客流预测数据查询请求参数
type FlowForecastTouristSummaryReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围和订单类型查询条件
	Unknown    bool                         `json:"unknown"`                         // 是否包含未知类型数据
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
}

// Api 返回API路径
func (r *FlowForecastTouristSummaryReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Unknown {
		params.Add("unknown", "true")
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/tourist/flow/forecast-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *FlowForecastTouristSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *FlowForecastTouristSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *FlowForecastTouristSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *FlowForecastTouristSummaryReq) AuthRequired() bool {
	return true
}

// FlowForecastTouristSummaryResp 客流预测数据查询响应结果
type FlowForecastTouristSummaryResp struct {
	Total *ForecastTouristTotal        `json:"total"` // 预测客流数据汇总
	List  []ForecastTouristSummaryList `json:"list"`  // 按日期详细预测数据列表
}

// ForecastTouristTotal 客流预测数据汇总
type ForecastTouristTotal struct {
	Today    int64 `json:"today"`    // 今日预测客流量
	Tomorrow int64 `json:"tomorrow"` // 明日预测客流量
	ThirdDay int64 `json:"thirdDay"` // 后天预测客流量
}

// ForecastTouristSummaryList 按日期客流预测数据详情
type ForecastTouristSummaryList struct {
	Date    int64                   `json:"date"`    // 日期时间戳
	Summary *ForecastTouristSummary `json:"summary"` // 该日期预测客流数据
}
