// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
	time "time"
)

// FlowTouristSummaryReq 客流统计数据查询请求参数
type FlowTouristSummaryReq struct {
	Request       *types.PassedTimeSpanRequest `json:"request"`                           // 时间范围和订单类型查询条件
	Unknown       bool                         `json:"unknown"`                           // 是否包含未知类型数据
	OrderType     types.OrderType              `json:"orderType"`                         // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid           []int64                      `json:"lid"`                               // 产品ID列表
	ExcludeLid    []int64                      `json:"excludeLid" cel:"odas.notexport"`   // 排除的产品ID列表
	Tid           []int64                      `json:"tid"`                               // 票种ID列表
	ExcludeTid    []int64                      `json:"excludeTid" cel:"odas.notexport"`   // 排除的票种ID列表
	DimensionType int64                        `json:"dimensionType" validate:"required"` // 统计维度类型：1-预订维度，2-验证维度
}

// Api 返回API路径
func (r *FlowTouristSummaryReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Unknown {
		params.Add("unknown", "true")
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	if r.DimensionType > 0 {
		params.Add("dimensionType", strconv.FormatInt(r.DimensionType, 10))
	}
	return fmt.Sprintf("/v5/tourist/flow/tourist-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *FlowTouristSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *FlowTouristSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *FlowTouristSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *FlowTouristSummaryReq) AuthRequired() bool {
	return true
}

// FlowTouristSummaryResp 客流统计数据查询响应结果
type FlowTouristSummaryResp struct {
	Total *ForecastTouristSummary `json:"total"` // 汇总客流数据
	List  []TouristSummaryList    `json:"list"`  // 按日期详细客流数据列表
}

// PassedTimeSpanRequest 时间范围请求参数
type PassedTimeSpanRequest struct {
	Sid      []int64        `json:"sid"`                       // 景区ID列表
	Start    time.Time      `json:"start" validate:"required"` // 开始时间: YYY-MM-DD; 如: 2021-01-01
	End      time.Time      `json:"end" validate:"required"`   // 结束时间: YYY-MM-DD; 如: 2021-01-01
	DateType types.DateType `json:"dateType"`                  // 日期类型(默认 0): 0 (DAILY)按日期范围; 1 (MONTHLY)只处理日期中的年和月然后整月查询; 2 (YEARLY)整年查询
}

// Params 将PassedTimeSpanRequest转换为url.Values
func (p PassedTimeSpanRequest) Params(prefix string) url.Values {
	params := url.Values{}
	if len(p.Sid) > 0 {
		for _, item := range p.Sid {
			params.Add(prefix+"sid", strconv.FormatInt(item, 10))
		}
	}
	if !p.Start.IsZero() {
		params.Add(prefix+"start", p.Start.Format("2006-01-02 15:04:05"))
	}
	if !p.End.IsZero() {
		params.Add(prefix+"end", p.End.Format("2006-01-02 15:04:05"))
	}
	if p.DateType > 0 {
		params.Add(prefix+"dateType", strconv.FormatInt(int64(p.DateType), 10))
	}
	return params
}

// ForecastTouristSummary 客流统计数据
type ForecastTouristSummary struct {
	Count int64 `json:"count"` // 客流数量
}

// TouristSummaryList 按日期客流统计数据详情
type TouristSummaryList struct {
	Date    int64                   `json:"date"`    // 日期时间戳
	Summary *ForecastTouristSummary `json:"summary"` // 该日期客流统计数据
}
