// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// PortraitTicketSummaryByPayChannelReq 按支付渠道门票统计数据查询请求参数
type PortraitTicketSummaryByPayChannelReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围和订单类型查询条件
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
	Limit      int64                        `json:"limit"`                           // 返回结果数量限制，用于分页
	Province   []string                     `json:"province"`                        // 省份名称列表，用于筛选特定省份下的支付渠道
}

// Api 返回API路径
func (r *PortraitTicketSummaryByPayChannelReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if len(r.Province) > 0 {
		for _, id := range r.Province {
			params.Add("province", id)
		}
	}
	return fmt.Sprintf("/v5/tourist/portrait/g-paychannel/ticket-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PortraitTicketSummaryByPayChannelReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PortraitTicketSummaryByPayChannelReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PortraitTicketSummaryByPayChannelReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PortraitTicketSummaryByPayChannelReq) AuthRequired() bool {
	return true
}

// PortraitTicketSummaryByPayChannelResp 按支付渠道门票统计数据查询响应结果
type PortraitTicketSummaryByPayChannelResp struct {
	Total *types.TouristSummary           `json:"total"` // 按支付渠道门票统计数据汇总
	List  []TicketSummaryByPayChannelList `json:"list"`  // 按支付渠道详细统计数据列表
}

// TicketSummaryByPayChannelList 按支付渠道门票统计数据详情
type TicketSummaryByPayChannelList struct {
	PayChannelId   int64              `json:"payChannelId"`   // 支付渠道ID
	PayChannelName string             `json:"payChannelName"` // 支付渠道名称
	Summary        *TicketSummary     `json:"summary"`        // 该渠道门票统计数据
	Rate           *TicketSummaryRate `json:"rate"`           // 该渠道占比数据
}

// TicketSummary 门票统计汇总数据
type TicketSummary struct {
	Amount      int64 `json:"amount"`      // 门票总金额
	TicketCount int64 `json:"ticketCount"` // 门票总数量
}

// TicketSummaryRate 门票统计占比数据
type TicketSummaryRate struct {
	Amount      float64 `json:"amount"`      // 门票金额占比
	TicketCount float64 `json:"ticketCount"` // 门票数量占比
}
