// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// PortraitSexSummaryByAgeReq 按年龄段统计性别分布请求参数
type PortraitSexSummaryByAgeReq struct {
	Request         *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	OrderType       types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	TicketId        []int64                      `json:"ticketId"`                        // 门票ID列表，用于筛选特定门票
	DimensionType   int64                        `json:"dimensionType"`                   // 统计维度类型：1-预订维度，2-验证维度；默认 1-预订维度
	Province        []string                     `json:"province"`                        // 省份名称列表，用于地域筛选
	Lid             []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid      []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid             []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid      []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
	ChannelLevel1Id []int64                      `json:"channelLevel1Id"`                 // 一级渠道ID，用于筛选指定一级渠道下的所有二级渠道
	ChannelLevel2Id []int64                      `json:"channelLevel2Id"`                 // 二级渠道ID，用于筛选指定二级渠道
}

// Api 返回API路径
func (r *PortraitSexSummaryByAgeReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.TicketId) > 0 {
		for _, id := range r.TicketId {
			params.Add("ticketId", strconv.FormatInt(id, 10))
		}
	}
	if r.DimensionType > 0 {
		params.Add("dimensionType", strconv.FormatInt(r.DimensionType, 10))
	}
	if len(r.Province) > 0 {
		for _, id := range r.Province {
			params.Add("province", id)
		}
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ChannelLevel1Id) > 0 {
		for _, id := range r.ChannelLevel1Id {
			params.Add("channelLevel1Id", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ChannelLevel2Id) > 0 {
		for _, id := range r.ChannelLevel2Id {
			params.Add("channelLevel2Id", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/tourist/portrait/g-age/sex-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PortraitSexSummaryByAgeReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PortraitSexSummaryByAgeReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PortraitSexSummaryByAgeReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PortraitSexSummaryByAgeReq) AuthRequired() bool {
	return true
}

// PortraitSexSummaryByAgeResp 按年龄段性别分布数据查询响应结果
type PortraitSexSummaryByAgeResp struct {
	Total *types.TouristSexSummary `json:"total"` // 性别年龄分布汇总统计数据
	List  []SexSummaryByAgeList    `json:"list"`  // 各年龄段性别分布详细统计列表
}

// TouristSexSummary 按年龄段性别分布汇总统计数据
type TouristSexSummary struct {
	Total   int64 `json:"total"`   // 游客总数量
	Male    int64 `json:"male"`    // 男性游客总数量
	Female  int64 `json:"female"`  // 女性游客总数量
	Unknown int64 `json:"unknown"` // 未知性别游客总数量
}

// SexSummaryByAgeList 按年龄段性别分布详细统计数据
type SexSummaryByAgeList struct {
	AgeGroup string      `json:"ageGroup"` // 年龄段标识（如：18-25岁）
	Summary  *SexSummary `json:"summary"`  // 该年龄段性别分布统计数据
}

// SexSummary 性别分布统计数据
type SexSummary struct {
	Female int64 `json:"female"` // 女性游客数量
	Male   int64 `json:"male"`   // 男性游客数量
}
