// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// PortraitInsideAndOutsideByProvinceReq 省内外游客来源统计请求参数
type PortraitInsideAndOutsideByProvinceReq struct {
	Request         *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围和订单类型查询条件
	Province        string                       `json:"province"`                        // 省份名称，用于筛选特定省份下的所有城市数据
	DimensionType   int64                        `json:"dimensionType"`                   // 统计维度类型：1-预订维度，2-验证维度；默认 1-预订维度
	Limit           int64                        `json:"limit"`                           // 返回结果数量限制，用于分页
	Unknown         bool                         `json:"unknown"`                         // 是否包含未知地区数据
	OrderType       types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid             []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid      []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid             []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid      []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
	ChannelLevel1Id []int64                      `json:"channelLevel1Id"`                 // 一级渠道ID，用于筛选指定一级渠道下的所有二级渠道
	ChannelLevel2Id []int64                      `json:"channelLevel2Id"`                 // 二级渠道ID，用于筛选指定二级渠道
}

// Api 返回API路径
func (r *PortraitInsideAndOutsideByProvinceReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Province != "" {
		params.Add("province", r.Province)
	}
	if r.DimensionType > 0 {
		params.Add("dimensionType", strconv.FormatInt(r.DimensionType, 10))
	}
	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if r.Unknown {
		params.Add("unknown", "true")
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ChannelLevel1Id) > 0 {
		for _, id := range r.ChannelLevel1Id {
			params.Add("channelLevel1Id", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ChannelLevel2Id) > 0 {
		for _, id := range r.ChannelLevel2Id {
			params.Add("channelLevel2Id", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/tourist/portrait/inside-and-outside?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PortraitInsideAndOutsideByProvinceReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PortraitInsideAndOutsideByProvinceReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PortraitInsideAndOutsideByProvinceReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PortraitInsideAndOutsideByProvinceReq) AuthRequired() bool {
	return true
}

// PortraitInsideAndOutsideByProvinceResp 省内外游客来源统计响应结果
type PortraitInsideAndOutsideByProvinceResp struct {
	Total   *InsideAndOutsideStatTotal `json:"total"`   // 省内外游客分布汇总统计数据
	Outside []OutsideList              `json:"outside"` // 省外各省份游客详细统计列表
	Inside  []InsideList               `json:"inside"`  // 省内各城市游客详细统计列表
}

// InsideAndOutsideStatTotal 省内外游客分布汇总统计数据
type InsideAndOutsideStatTotal struct {
	InsideProvince  int64   `json:"insideProvince"`  // 省内游客总数量
	InsideRate      float64 `json:"insideRate"`      // 省内游客占比
	OutsideProvince int64   `json:"outsideProvince"` // 省外游客总数量
	OutsideRate     float64 `json:"outsideRate"`     // 省外游客占比
}

// OutsideList 省外省份游客详细统计数据
type OutsideList struct {
	Province string  `json:"province"` // 省外省份名称
	Count    int64   `json:"count"`    // 该省份游客数量
	Rate     float64 `json:"rate"`     // 该省份在省外游客中的占比
}

// InsideList 省内城市游客详细统计数据
type InsideList struct {
	City  string  `json:"city"`  // 省内城市名称
	Count int64   `json:"count"` // 该城市游客数量
	Rate  float64 `json:"rate"`  // 该城市在省内游客中的占比
}
