// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// PortraitTouristSummaryByPeerReq 按同行人数游客统计数据查询请求参数
type PortraitTouristSummaryByPeerReq struct {
	Request         *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围和订单类型查询条件
	Province        string                       `json:"province"`                        // 省份名称，用于筛选特定省份的游客数据
	OrderType       types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid             []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid      []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid             []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid      []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
	ChannelLevel1Id []int64                      `json:"channelLevel1Id"`                 // 一级渠道ID，用于筛选指定一级渠道下的所有二级渠道
	ChannelLevel2Id []int64                      `json:"channelLevel2Id"`                 // 二级渠道ID，用于筛选指定二级渠道
}

// Api 返回API路径
func (r *PortraitTouristSummaryByPeerReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Province != "" {
		params.Add("province", r.Province)
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ChannelLevel1Id) > 0 {
		for _, id := range r.ChannelLevel1Id {
			params.Add("channelLevel1Id", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ChannelLevel2Id) > 0 {
		for _, id := range r.ChannelLevel2Id {
			params.Add("channelLevel2Id", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/tourist/portrait/g-peer/tourist-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PortraitTouristSummaryByPeerReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PortraitTouristSummaryByPeerReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PortraitTouristSummaryByPeerReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PortraitTouristSummaryByPeerReq) AuthRequired() bool {
	return true
}

// PortraitTouristSummaryByPeerResp 按同行人数游客统计数据查询响应结果
type PortraitTouristSummaryByPeerResp struct {
	Total *types.TouristSummary      `json:"total"` // 同行人数游客分布汇总统计数据
	List  []TouristSummaryByPeerList `json:"list"`  // 各同行人数游客分布详细统计列表
}

// TouristSummaryByPeerList 按同行人数游客统计数据详情
type TouristSummaryByPeerList struct {
	PeerGroup string                `json:"peerGroup"` // 同行人数分组标识
	Summary   *types.TouristSummary `json:"summary"`   // 该分组游客统计数据
	Rate      float64               `json:"rate"`      // 该分组在总体中的占比
}
