// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
	time "time"
)

// PortraitTouristSummaryByProvinceReq 按省份游客统计数据查询请求参数
type PortraitTouristSummaryByProvinceReq struct {
	Request         *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围查询条件
	Compare         *types.PassedTimeSpan        `json:"compare"`                         // 对比时间范围
	OrderType       types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	DimensionType   int64                        `json:"dimensionType"`                   // 统计维度类型：1-预订维度，2-验证维度；默认 1-预订维度
	Limit           int64                        `json:"limit"`                           // 返回记录数量限制，用于分页
	Lid             []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid      []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid             []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid      []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
	ChannelLevel1Id []int64                      `json:"channelLevel1Id"`                 // 一级渠道ID，用于筛选指定一级渠道下的所有二级渠道
	ChannelLevel2Id []int64                      `json:"channelLevel2Id"`                 // 二级渠道ID，用于筛选指定二级渠道
}

// Api 返回API路径
func (r *PortraitTouristSummaryByProvinceReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Compare != nil {
		for key, values := range r.Compare.Params("compare.") {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if r.DimensionType > 0 {
		params.Add("dimensionType", strconv.FormatInt(r.DimensionType, 10))
	}
	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ChannelLevel1Id) > 0 {
		for _, id := range r.ChannelLevel1Id {
			params.Add("channelLevel1Id", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ChannelLevel2Id) > 0 {
		for _, id := range r.ChannelLevel2Id {
			params.Add("channelLevel2Id", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/tourist/portrait/g-province/tourist-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PortraitTouristSummaryByProvinceReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PortraitTouristSummaryByProvinceReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PortraitTouristSummaryByProvinceReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PortraitTouristSummaryByProvinceReq) AuthRequired() bool {
	return true
}

// PortraitTouristSummaryByProvinceResp 按省份游客统计数据查询响应结果
type PortraitTouristSummaryByProvinceResp struct {
	Total *types.TouristSummary          `json:"total"` // 省份游客分布汇总统计数据
	List  []TouristSummaryByProvinceList `json:"list"`  // 各省份游客分布详细统计列表
}

// PassedTimeSpan 时间范围
type PassedTimeSpan struct {
	Start time.Time `json:"start"` // 开始时间: YYY-MM-DD; 如: 2021-01-01
	End   time.Time `json:"end"`   // 结束时间: YYY-MM-DD; 如: 2021-01-01
}

// Params 将PassedTimeSpan转换为url.Values
func (p PassedTimeSpan) Params(prefix string) url.Values {
	params := url.Values{}
	if !p.Start.IsZero() {
		params.Add(prefix+"start", p.Start.Format("2006-01-02 15:04:05"))
	}
	if !p.End.IsZero() {
		params.Add(prefix+"end", p.End.Format("2006-01-02 15:04:05"))
	}
	return params
}

// TouristSummary 游客统计汇总数据 Tourist Summary
type TouristSummary struct {
	Count int64 `json:"count"` // 游客总数量
}

// TouristSummaryByProvinceList 按省份游客统计数据详情
type TouristSummaryByProvinceList struct {
	Province         string                `json:"province"`         // 省份名称
	Summary          *types.TouristSummary `json:"summary"`          // 该省份游客统计数据
	Rate             float64               `json:"rate"`             // 在总体的占比
	CompareTotalRate float64               `json:"compareTotalRate"` // 对比期间占比
}
