// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// PreBookingSummaryReq 提前预订统计数据查询请求参数
type PreBookingSummaryReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围和订单类型查询条件
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
}

// Api 返回API路径
func (r *PreBookingSummaryReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/tourist/pre-booking/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PreBookingSummaryReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PreBookingSummaryReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PreBookingSummaryReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PreBookingSummaryReq) AuthRequired() bool {
	return true
}

// PreBookingSummaryResp 提前预订统计数据查询响应结果
type PreBookingSummaryResp struct {
	Total *PreBookingSummary             `json:"total"` // 汇总预订数据
	List  []PreBookingServiceSummaryList `json:"list"`  // 按日期详细预订数据列表
}

// PreBookingSummary 提前预订统计数据
type PreBookingSummary struct {
	OrderNum    int64 `json:"orderNum"`    // 预订订单数量
	OrderTicket int64 `json:"orderTicket"` // 预订门票数量
	OrderAmount int64 `json:"orderAmount"` // 预订订单金额
}

// PreBookingServiceSummaryList 按日期提前预订统计数据详情
type PreBookingServiceSummaryList struct {
	Time    string             `json:"time"`    // 日期时间
	Summary *PreBookingSummary `json:"summary"` // 该日期预订统计数据
}
