// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// PreBookingSummaryByTypeReq 按预购时长分组统计数据查询请求参数
type PreBookingSummaryByTypeReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围和订单类型查询条件
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Tid        []int64                      `json:"tid"`                             // 票种ID列表
	ExcludeTid []int64                      `json:"excludeTid" cel:"odas.notexport"` // 排除的票种ID列表
}

// Api 返回API路径
func (r *PreBookingSummaryByTypeReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Tid) > 0 {
		for _, id := range r.Tid {
			params.Add("tid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeTid) > 0 {
		for _, id := range r.ExcludeTid {
			params.Add("excludeTid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/tourist/pre-booking/g-type/summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PreBookingSummaryByTypeReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PreBookingSummaryByTypeReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PreBookingSummaryByTypeReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PreBookingSummaryByTypeReq) AuthRequired() bool {
	return true
}

// PreBookingSummaryByTypeResp 按预购时长分组统计数据查询响应结果
type PreBookingSummaryByTypeResp struct {
	Total *PreBookingSummary  `json:"total"` // 汇总预订数据
	List  []SummaryByTypeList `json:"list"`  // 按预购时长分组详细数据列表
}

// SummaryByTypeList 按预购时长分组统计数据详情
type SummaryByTypeList struct {
	TypeName string             `json:"typeName"` // 预购时长分组名称
	Summary  *PreBookingSummary `json:"summary"`  // 该分组预订统计数据
	Percent  float64            `json:"percent"`  // 该分组占比
}
