// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// PreBookingTouristSummaryByProvinceAndDateReq 按省份游客统计数据查询请求参数
type PreBookingTouristSummaryByProvinceAndDateReq struct {
	Request       *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围查询条件
	Compare       *types.PassedTimeSpan        `json:"compare"`                         // 对比时间范围
	OrderType     types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	DimensionType int64                        `json:"dimensionType"`                   // 统计维度类型：1-预订维度，2-验证维度；默认 1-预订维度
	Limit         int64                        `json:"limit"`                           // 返回记录数量限制，用于分页
	Lid           []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid    []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
}

// Api 返回API路径
func (r *PreBookingTouristSummaryByProvinceAndDateReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.Compare != nil {
		for key, values := range r.Compare.Params("compare.") {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}
	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if r.DimensionType > 0 {
		params.Add("dimensionType", strconv.FormatInt(r.DimensionType, 10))
	}
	if r.Limit > 0 {
		params.Add("limit", strconv.FormatInt(r.Limit, 10))
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	return fmt.Sprintf("/v5/tourist/pre-booking/g-province-date/tourist-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PreBookingTouristSummaryByProvinceAndDateReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PreBookingTouristSummaryByProvinceAndDateReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PreBookingTouristSummaryByProvinceAndDateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PreBookingTouristSummaryByProvinceAndDateReq) AuthRequired() bool {
	return true
}

// PreBookingTouristSummaryByProvinceAndDateResp 按省份游客统计数据查询响应结果
type PreBookingTouristSummaryByProvinceAndDateResp struct {
	Total *types.TouristSummary                 `json:"total"` // 省份游客分布汇总统计数据
	List  []TouristSummaryByProvinceAndDateList `json:"list"`  // 各省份游客分布详细统计列表
}

// TouristSummaryByProvinceAndDateList 按省份游客统计数据详情
type TouristSummaryByProvinceAndDateList struct {
	Ymd      int64                 `json:"ymd"`      // 数字类型日期 YYYYMMDD
	Date     string                `json:"date"`     // 日期
	Province string                `json:"province"` // 省份名称
	Summary  *types.TouristSummary `json:"summary"`  // 该省份游客统计数据
}
