// Code generated by sdk-generator. DO NOT EDIT.
// 此文件由代码生成器自动生成，请勿手动修改

package tourist

import (
	"fmt"
	"net/url"

	types "github.com/piaofutong/odas-sdk/odas/common"
	strconv "strconv"
)

// PreBookingTouristSexSummaryByAgeAndDateReq 按年龄段统计性别分布请求参数
type PreBookingTouristSexSummaryByAgeAndDateReq struct {
	Request    *types.PassedTimeSpanRequest `json:"request"`                         // 时间范围请求参数
	OrderType  types.OrderType              `json:"orderType"`                       // 订单类型(默认0): 0=主订单 1=子订单 2=全部订单
	TicketId   []int64                      `json:"ticketId"`                        // 门票ID列表，用于筛选特定门票
	Lid        []int64                      `json:"lid"`                             // 产品ID列表
	ExcludeLid []int64                      `json:"excludeLid" cel:"odas.notexport"` // 排除的产品ID列表
	Province   []string                     `json:"province"`                        // 省份名称列表，用于地域筛选
}

// Api 返回API路径
func (r *PreBookingTouristSexSummaryByAgeAndDateReq) Api() string {
	params := url.Values{}
	if r.Request != nil {
		requestParams := r.Request.Params("")
		for key, values := range requestParams {
			for _, value := range values {
				params.Add(key, value)
			}
		}
	}

	if r.OrderType > 0 {
		params.Add("orderType", strconv.FormatInt(int64(r.OrderType), 10))
	}
	if len(r.TicketId) > 0 {
		for _, id := range r.TicketId {
			params.Add("ticketId", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Lid) > 0 {
		for _, id := range r.Lid {
			params.Add("lid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.ExcludeLid) > 0 {
		for _, id := range r.ExcludeLid {
			params.Add("excludeLid", strconv.FormatInt(id, 10))
		}
	}
	if len(r.Province) > 0 {
		for _, id := range r.Province {
			params.Add("province", id)
		}
	}
	return fmt.Sprintf("/v5/tourist/pre-booking/g-age-date/touristsex-summary?%s", params.Encode())

}

// Method 返回HTTP方法
func (r *PreBookingTouristSexSummaryByAgeAndDateReq) Method() string {
	return "GET"
}

// Body 返回请求体
func (r *PreBookingTouristSexSummaryByAgeAndDateReq) Body() []byte {
	return nil

}

// ContentType 返回内容类型
func (r *PreBookingTouristSexSummaryByAgeAndDateReq) ContentType() string {
	return "application/json"
}

// AuthRequired 返回是否需要认证
func (r *PreBookingTouristSexSummaryByAgeAndDateReq) AuthRequired() bool {
	return true
}

// PreBookingTouristSexSummaryByAgeAndDateResp 按年龄段性别分布数据查询响应结果
type PreBookingTouristSexSummaryByAgeAndDateResp struct {
	Total *types.TouristSexSummary            `json:"total"` // 性别年龄分布汇总统计数据
	List  []TouristSexSummaryByAgeAndDateList `json:"list"`  // 各年龄段性别分布详细统计列表
}

// TouristSexSummaryByAgeAndDateList 按年龄段性别分布详细统计数据
type TouristSexSummaryByAgeAndDateList struct {
	Date     string                   `json:"date"`     // 日期
	AgeGroup string                   `json:"ageGroup"` // 年龄段标识（如：18-25岁）
	Summary  *types.TouristSexSummary `json:"summary"`  // 该年龄段性别分布统计数据
}
